
var f;f||(f=typeof Module !== 'undefined' ? Module : {});var h={},l;for(l in f)f.hasOwnProperty(l)&&(h[l]=f[l]);var m=[],aa="./this.program";function r(a,b){throw b;}var ca=!1,u=!1,w=!1,da=!1;ca="object"===typeof window;u="function"===typeof importScripts;w="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;da=!ca&&!w&&!u;var x="",ea,fa,y,ha,ia;
if(w)x=u?require("path").dirname(x)+"/":__dirname+"/",ea=function(a,b){ha||(ha=require("fs"));ia||(ia=require("path"));a=ia.normalize(a);return ha.readFileSync(a,b?null:"utf8")},y=function(a){a=ea(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(aa=process.argv[1].replace(/\\/g,"/")),m=process.argv.slice(2),"undefined"!==typeof module&&(module.exports=f),process.on("uncaughtException",function(a){if(!(a instanceof ja))throw a;}),process.on("unhandledRejection",
z),r=function(a){process.exit(a)},f.inspect=function(){return"[Emscripten Module object]"};else if(da)"undefined"!=typeof read&&(ea=function(a){return read(a)}),y=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?m=scriptArgs:"undefined"!=typeof arguments&&(m=arguments),"function"===typeof quit&&(r=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&
(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(ca||u)u?x=self.location.href:"undefined"!==typeof document&&document.currentScript&&(x=document.currentScript.src),x=0!==x.indexOf("blob:")?x.substr(0,x.lastIndexOf("/")+1):"",ea=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},u&&(y=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),
fa=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var ka=f.print||console.log.bind(console),A=f.printErr||console.warn.bind(console);for(l in h)h.hasOwnProperty(l)&&(f[l]=h[l]);h=null;f.arguments&&(m=f.arguments);f.thisProgram&&(aa=f.thisProgram);f.quit&&(r=f.quit);var C;f.wasmBinary&&(C=f.wasmBinary);var noExitRuntime=f.noExitRuntime||!0;
"object"!==typeof WebAssembly&&z("no native wasm support detected");var la,ma=!1;function assert(a,b){a||z("Assertion failed: "+b)}function na(a){var b=f["_"+a];assert(b,"Cannot call unknown function "+a+", make sure it is exported");return b}
function oa(a,b,c,d){var e={string:function(n){var t=0;if(null!==n&&void 0!==n&&0!==n){var v=(n.length<<2)+1;t=D(v);pa(n,E,t,v)}return t},array:function(n){var t=D(n.length);F.set(n,t);return t}},g=na(a),k=[];a=0;if(d)for(var p=0;p<d.length;p++){var q=e[c[p]];q?(0===a&&(a=qa()),k[p]=q(d[p])):k[p]=d[p]}c=g.apply(null,k);c=function(n){return"string"===b?n?G(E,n,void 0):"":"boolean"===b?!!n:n}(c);0!==a&&ra(a);return c}var sa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function G(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&sa)return sa.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var k=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|k:(e&7)<<18|g<<12|k<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}
function pa(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var k=a.charCodeAt(g);if(55296<=k&&57343>=k){var p=a.charCodeAt(++g);k=65536+((k&1023)<<10)|p&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-e}
function ta(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function ua(a){var b=ta(a)+1,c=va(b);c&&pa(a,F,c,b);return c}function wa(a){var b=ta(a)+1,c=D(b);pa(a,F,c,b);return c}var xa,F,E,ya,H,za,Aa=[],Ba=[],Ca=[],Da=[];function Ea(){var a=f.preRun.shift();Aa.unshift(a)}var J=0,Fa=null,K=null;f.preloadedImages={};f.preloadedAudios={};
function z(a){if(f.onAbort)f.onAbort(a);A(a);ma=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function Ga(){return L.startsWith("data:application/octet-stream;base64,")}var L="bumblestack.wasm";if(!Ga()){var Ha=L;L=f.locateFile?f.locateFile(Ha,x):x+Ha}function Ja(){var a=L;try{if(a==L&&C)return new Uint8Array(C);if(y)return y(a);throw"both async and sync fetching of the wasm failed";}catch(b){z(b)}}
function Ka(){if(!C&&(ca||u)){if("function"===typeof fetch&&!L.startsWith("file://"))return fetch(L,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+L+"'";return a.arrayBuffer()}).catch(function(){return Ja()});if(fa)return new Promise(function(a,b){fa(L,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return Ja()})}var N,La;
function Ma(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(f);else{var c=b.oa;"number"===typeof c?void 0===b.S?za.get(c)():za.get(c)(b.S):c(void 0===b.S?null:b.S)}}}function Na(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}
function Oa(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Na(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}function Pa(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function Qa(a){if("/"===a)return"/";a=Oa(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function Ra(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(w)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){z("randomDevice")}}
function Sa(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Na(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var Ta=[];function Ua(a,b){Ta[a]={input:[],output:[],O:b};Va(a,Wa)}
var Wa={open:function(a){var b=Ta[a.node.rdev];if(!b)throw new O(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.O.flush(a.tty)},flush:function(a){a.tty.O.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.O.aa)throw new O(60);for(var e=0,g=0;g<d;g++){try{var k=a.tty.O.aa(a.tty)}catch(p){throw new O(29);}if(void 0===k&&0===e)throw new O(6);if(null===k||void 0===k)break;e++;b[c+g]=k}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.O.U)throw new O(60);try{for(var e=
0;e<d;e++)a.tty.O.U(a.tty,b[c+e])}catch(g){throw new O(29);}d&&(a.node.timestamp=Date.now());return e}},Xa={aa:function(a){if(!a.input.length){var b=null;if(w){var c=Buffer.fa?Buffer.fa(256):new Buffer(256),d=0;try{d=ha.readSync(process.stdin.fd,c,0,256,null)}catch(e){if(e.toString().includes("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&
(b=readline(),null!==b&&(b+="\n"));if(!b)return null;c=Array(ta(b)+1);b=pa(b,c,0,c.length);c.length=b;a.input=c}return a.input.shift()},U:function(a,b){null===b||10===b?(ka(G(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(ka(G(a.output,0)),a.output=[])}},Ya={U:function(a,b){null===b||10===b?(A(G(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(A(G(a.output,0)),a.output=[])}},P={I:null,K:function(){return P.createNode(null,
"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new O(63);P.I||(P.I={dir:{node:{L:P.F.L,J:P.F.J,lookup:P.F.lookup,P:P.F.P,rename:P.F.rename,unlink:P.F.unlink,rmdir:P.F.rmdir,readdir:P.F.readdir,symlink:P.F.symlink},stream:{N:P.G.N}},file:{node:{L:P.F.L,J:P.F.J},stream:{N:P.G.N,read:P.G.read,write:P.G.write,W:P.G.W,ba:P.G.ba,ea:P.G.ea}},link:{node:{L:P.F.L,J:P.F.J,readlink:P.F.readlink},stream:{}},X:{node:{L:P.F.L,J:P.F.J},stream:Za}});c=$a(a,b,c,d);16384===
(c.mode&61440)?(c.F=P.I.dir.node,c.G=P.I.dir.stream,c.D={}):32768===(c.mode&61440)?(c.F=P.I.file.node,c.G=P.I.file.stream,c.H=0,c.D=null):40960===(c.mode&61440)?(c.F=P.I.link.node,c.G=P.I.link.stream):8192===(c.mode&61440)&&(c.F=P.I.X.node,c.G=P.I.X.stream);c.timestamp=Date.now();a&&(a.D[b]=c,a.timestamp=c.timestamp);return c},pa:function(a){return a.D?a.D.subarray?a.D.subarray(0,a.H):new Uint8Array(a.D):new Uint8Array(0)},Y:function(a,b){var c=a.D?a.D.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:
1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.D,a.D=new Uint8Array(b),0<a.H&&a.D.set(c.subarray(0,a.H),0))},ka:function(a,b){if(a.H!=b)if(0==b)a.D=null,a.H=0;else{var c=a.D;a.D=new Uint8Array(b);c&&a.D.set(c.subarray(0,Math.min(b,a.H)));a.H=b}},F:{L:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.H:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);
b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.ga=4096;b.blocks=Math.ceil(b.size/b.ga);return b},J:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&P.ka(a,b.size)},lookup:function(){throw ab[44];},P:function(a,b,c,d){return P.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=bb(b,c)}catch(g){}if(d)for(var e in d.D)throw new O(55);}delete a.parent.D[a.name];a.parent.timestamp=Date.now();a.name=
c;b.D[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink:function(a,b){delete a.D[b];a.timestamp=Date.now()},rmdir:function(a,b){var c=bb(a,b),d;for(d in c.D)throw new O(55);delete a.D[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.D)a.D.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=P.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new O(28);return a.link}},G:{read:function(a,b,c,d,e){var g=a.node.D;
if(e>=a.node.H)return 0;a=Math.min(a.node.H-e,d);if(8<a&&g.subarray)b.set(g.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=g[e+d];return a},write:function(a,b,c,d,e,g){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.D||a.D.subarray)){if(g)return a.D=b.subarray(c,c+d),a.H=d;if(0===a.H&&0===e)return a.D=b.slice(c,c+d),a.H=d;if(e+d<=a.H)return a.D.set(b.subarray(c,c+d),e),d}P.Y(a,e+d);if(a.D.subarray&&b.subarray)a.D.set(b.subarray(c,c+d),e);else for(g=0;g<d;g++)a.D[e+g]=b[c+g];a.H=
Math.max(a.H,e+d);return d},N:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.H);if(0>b)throw new O(28);return b},W:function(a,b,c){P.Y(a.node,b+c);a.node.H=Math.max(a.node.H,b+c)},ba:function(a,b,c,d,e,g){if(0!==b)throw new O(28);if(32768!==(a.node.mode&61440))throw new O(43);a=a.node.D;if(g&2||a.buffer!==xa){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;g=65536*Math.ceil(c/65536);for(b=va(g);c<g;)F[b+c++]=0;c=b;
if(!c)throw new O(48);F.set(a,c)}else d=!1,c=a.byteOffset;return{ra:c,na:d}},ea:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new O(43);if(e&2)return 0;P.G.write(a,b,0,d,c,!1);return 0}}},cb=null,db={},Q=[],eb=1,R=null,fb=!0,gb={},O=null,ab={};
function S(a,b){a=Sa("/",a);b=b||{};if(!a)return{path:"",node:null};var c={$:!0,V:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.V)throw new O(32);a=Na(a.split("/").filter(function(k){return!!k}),!1);var e=cb;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;e=bb(e,a[d]);c=Oa(c+"/"+a[d]);e.R&&(!g||g&&b.$)&&(e=e.R.root);if(!g||b.Z)for(g=0;40960===(e.mode&61440);)if(e=hb(c),c=Sa(Pa(c),e),e=S(c,{V:b.V}).node,40<g++)throw new O(32);}return{path:c,node:e}}
function ib(a){for(var b;;){if(a===a.parent)return a=a.K.da,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function jb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%R.length}function bb(a,b){var c;if(c=(c=kb(a,"x"))?c:a.F.lookup?0:2)throw new O(c,a);for(c=R[jb(a.id,b)];c;c=c.ja){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.F.lookup(a,b)}
function $a(a,b,c,d){a=new lb(a,b,c,d);b=jb(a.parent.id,a.name);a.ja=R[b];return R[b]=a}var mb={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090};function nb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function kb(a,b){if(fb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function ob(a,b){try{return bb(a,b),20}catch(c){}return kb(a,"wx")}
function pb(a){var b=4096;for(a=a||0;a<=b;a++)if(!Q[a])return a;throw new O(33);}function qb(a,b){rb||(rb=function(){},rb.prototype={});var c=new rb,d;for(d in a)c[d]=a[d];a=c;b=pb(b);a.fd=b;return Q[b]=a}var Za={open:function(a){a.G=db[a.node.rdev].G;a.G.open&&a.G.open(a)},N:function(){throw new O(70);}};function Va(a,b){db[a]={G:b}}
function sb(a,b){var c="/"===b,d=!b;if(c&&cb)throw new O(10);if(!c&&!d){var e=S(b,{$:!1});b=e.path;e=e.node;if(e.R)throw new O(10);if(16384!==(e.mode&61440))throw new O(54);}b={type:a,qa:{},da:b,ia:[]};a=a.K(b);a.K=b;b.root=a;c?cb=a:e&&(e.R=b,e.K&&e.K.ia.push(b))}function tb(a,b,c){var d=S(a,{parent:!0}).node;a=Qa(a);if(!a||"."===a||".."===a)throw new O(28);var e=ob(d,a);if(e)throw new O(e);if(!d.F.P)throw new O(63);return d.F.P(d,a,b,c)}function T(a){return tb(a,16895,0)}
function ub(a,b,c){"undefined"===typeof c&&(c=b,b=438);tb(a,b|8192,c)}function vb(a,b){if(!Sa(a))throw new O(44);var c=S(b,{parent:!0}).node;if(!c)throw new O(44);b=Qa(b);var d=ob(c,b);if(d)throw new O(d);if(!c.F.symlink)throw new O(63);c.F.symlink(c,b,a)}function hb(a){a=S(a).node;if(!a)throw new O(44);if(!a.F.readlink)throw new O(28);return Sa(ib(a.parent),a.F.readlink(a))}
function U(a,b,c,d){if(""===a)throw new O(44);if("string"===typeof b){var e=mb[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var g=a;else{a=Oa(a);try{g=S(a,{Z:!(b&131072)}).node}catch(k){}}e=!1;if(b&64)if(g){if(b&128)throw new O(20);}else g=tb(a,c,0),e=!0;if(!g)throw new O(44);8192===(g.mode&61440)&&(b&=-513);if(b&65536&&16384!==(g.mode&61440))throw new O(54);if(!e&&(c=g?40960===(g.mode&61440)?32:
16384===(g.mode&61440)&&("r"!==nb(b)||b&512)?31:kb(g,nb(b)):44))throw new O(c);if(b&512){c=g;c="string"===typeof c?S(c,{Z:!0}).node:c;if(!c.F.J)throw new O(63);if(16384===(c.mode&61440))throw new O(31);if(32768!==(c.mode&61440))throw new O(28);if(e=kb(c,"w"))throw new O(e);c.F.J(c,{size:0,timestamp:Date.now()})}b&=-131713;d=qb({node:g,path:ib(g),flags:b,seekable:!0,position:0,G:g.G,ma:[],error:!1},d);d.G.open&&d.G.open(d);!f.logReadFiles||b&1||(wb||(wb={}),a in wb||(wb[a]=1,A("FS.trackingDelegate error on read file: "+
a)));try{gb.onOpenFile&&(g=0,1!==(b&2097155)&&(g|=1),0!==(b&2097155)&&(g|=2),gb.onOpenFile(a,g))}catch(k){A("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+k.message)}return d}function xb(a,b,c){if(null===a.fd)throw new O(8);if(!a.seekable||!a.G.N)throw new O(70);if(0!=c&&1!=c&&2!=c)throw new O(28);a.position=a.G.N(a,b,c);a.ma=[]}
function yb(){O||(O=function(a,b){this.node=b;this.la=function(c){this.M=c};this.la(a);this.message="FS error"},O.prototype=Error(),O.prototype.constructor=O,[44].forEach(function(a){ab[a]=new O(a);ab[a].stack="<generic error, no stack>"}))}var zb;function Ab(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function V(a,b,c){a=Oa("/dev/"+a);var d=Ab(!!b,!!c);Bb||(Bb=64);var e=Bb++<<8|0;Va(e,{open:function(g){g.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(g,k,p,q){for(var n=0,t=0;t<q;t++){try{var v=b()}catch(I){throw new O(29);}if(void 0===v&&0===n)throw new O(6);if(null===v||void 0===v)break;n++;k[p+t]=v}n&&(g.node.timestamp=Date.now());return n},write:function(g,k,p,q){for(var n=0;n<q;n++)try{c(k[p+n])}catch(t){throw new O(29);}q&&(g.node.timestamp=Date.now());return n}});
ub(a,d,e)}var Bb,W={},rb,wb,Cb=void 0;function X(){Cb+=4;return H[Cb-4>>2]}function Y(a){a=Q[a];if(!a)throw new O(8);return a}function Db(){function a(k){return(k=k.toTimeString().match(/\(([A-Za-z ]+)\)$/))?k[1]:"GMT"}if(!Eb){Eb=!0;var b=(new Date).getFullYear(),c=new Date(b,0,1),d=new Date(b,6,1);b=c.getTimezoneOffset();var e=d.getTimezoneOffset(),g=Math.max(b,e);H[Fb()>>2]=60*g;H[Gb()>>2]=Number(b!=e);c=a(c);d=a(d);c=ua(c);d=ua(d);e<b?(H[Z()>>2]=c,H[Z()+4>>2]=d):(H[Z()>>2]=d,H[Z()+4>>2]=c)}}var Eb;
function Hb(){A("missing function: wrenFreeVM");z(-1)}f._wrenFreeVM=Hb;function lb(a,b,c,d){a||(a=this);this.parent=a;this.K=a.K;this.R=null;this.id=eb++;this.name=b;this.mode=c;this.F={};this.G={};this.rdev=d}Object.defineProperties(lb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});yb();R=Array(4096);sb(P,"/");T("/tmp");T("/home");
T("/home/web_user");(function(){T("/dev");Va(259,{read:function(){return 0},write:function(b,c,d,e){return e}});ub("/dev/null",259);Ua(1280,Xa);Ua(1536,Ya);ub("/dev/tty",1280);ub("/dev/tty1",1536);var a=Ra();V("random",a);V("urandom",a);T("/dev/shm");T("/dev/shm/tmp")})();
(function(){T("/proc");var a=T("/proc/self");T("/proc/self/fd");sb({K:function(){var b=$a(a,"fd",16895,73);b.F={lookup:function(c,d){var e=Q[+d];if(!e)throw new O(8);c={parent:null,K:{da:"fake"},F:{readlink:function(){return e.path}}};return c.parent=c}};return b}},"/proc/self/fd")})();
var Kb={c:function(a,b,c){Cb=c;try{var d=Y(a);switch(b){case 0:var e=X();return 0>e?-28:U(d.path,d.flags,0,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=X(),d.flags|=e,0;case 12:return e=X(),ya[e+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return H[Ib()>>2]=28,-1;default:return-28}}catch(g){return"undefined"!==typeof W&&g instanceof O||z(g),-g.M}},n:function(a,b,c){Cb=c;try{var d=Y(a);switch(b){case 21509:case 21505:return d.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.tty?
0:-59;case 21519:if(!d.tty)return-59;var e=X();return H[e>>2]=0;case 21520:return d.tty?-28:-59;case 21531:a=e=X();if(!d.G.ha)throw new O(59);return d.G.ha(d,b,a);case 21523:return d.tty?0:-59;case 21524:return d.tty?0:-59;default:z("bad ioctl syscall "+b)}}catch(g){return"undefined"!==typeof W&&g instanceof O||z(g),-g.M}},e:function(a,b,c){Cb=c;try{var d=a?G(E,a,void 0):"",e=c?X():0;return U(d,b,e).fd}catch(g){return"undefined"!==typeof W&&g instanceof O||z(g),-g.M}},l:function(a,b,c){E.copyWithin(a,
b,b+c)},m:function(){z("OOM")},a:function(a){Jb(a)},b:function(a){try{var b=Y(a);if(null===b.fd)throw new O(8);b.T&&(b.T=null);try{b.G.close&&b.G.close(b)}catch(c){throw c;}finally{Q[b.fd]=null}b.fd=null;return 0}catch(c){return"undefined"!==typeof W&&c instanceof O||z(c),c.M}},o:function(a,b,c,d){try{a:{for(var e=Y(a),g=a=0;g<c;g++){var k=H[b+(8*g+4)>>2],p=e,q=H[b+8*g>>2],n=k,t=void 0,v=F;if(0>n||0>t)throw new O(28);if(null===p.fd)throw new O(8);if(1===(p.flags&2097155))throw new O(8);if(16384===
(p.node.mode&61440))throw new O(31);if(!p.G.read)throw new O(28);var I="undefined"!==typeof t;if(!I)t=p.position;else if(!p.seekable)throw new O(70);var ba=p.G.read(p,v,q,n,t);I||(p.position+=ba);var M=ba;if(0>M){var B=-1;break a}a+=M;if(M<k)break}B=a}H[d>>2]=B;return 0}catch(Ia){return"undefined"!==typeof W&&Ia instanceof O||z(Ia),Ia.M}},k:function(a,b,c,d,e){try{var g=Y(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;xb(g,a,d);La=[g.position>>>0,(N=g.position,1<=
+Math.abs(N)?0<N?(Math.min(+Math.floor(N/4294967296),4294967295)|0)>>>0:~~+Math.ceil((N-+(~~N>>>0))/4294967296)>>>0:0)];H[e>>2]=La[0];H[e+4>>2]=La[1];g.T&&0===a&&0===d&&(g.T=null);return 0}catch(k){return"undefined"!==typeof W&&k instanceof O||z(k),k.M}},d:function(a,b,c,d){try{a:{for(var e=Y(a),g=a=0;g<c;g++){var k=e,p=H[b+8*g>>2],q=H[b+(8*g+4)>>2],n=void 0,t=F;if(0>q||0>n)throw new O(28);if(null===k.fd)throw new O(8);if(0===(k.flags&2097155))throw new O(8);if(16384===(k.node.mode&61440))throw new O(31);
if(!k.G.write)throw new O(28);k.seekable&&k.flags&1024&&xb(k,0,2);var v="undefined"!==typeof n;if(!v)n=k.position;else if(!k.seekable)throw new O(70);var I=k.G.write(k,t,p,q,n,void 0);v||(k.position+=I);try{if(k.path&&gb.onWriteToFile)gb.onWriteToFile(k.path)}catch(B){A("FS.trackingDelegate['onWriteToFile']('"+k.path+"') threw an exception: "+B.message)}var ba=I;if(0>ba){var M=-1;break a}a+=ba}M=a}H[d>>2]=M;return 0}catch(B){return"undefined"!==typeof W&&B instanceof O||z(B),B.M}},f:function(a){var b=
Date.now();H[a>>2]=b/1E3|0;H[a+4>>2]=b%1E3*1E3|0;return 0},g:function(a,b){Db();a=new Date(1E3*H[a>>2]);H[b>>2]=a.getSeconds();H[b+4>>2]=a.getMinutes();H[b+8>>2]=a.getHours();H[b+12>>2]=a.getDate();H[b+16>>2]=a.getMonth();H[b+20>>2]=a.getFullYear()-1900;H[b+24>>2]=a.getDay();var c=new Date(a.getFullYear(),0,1);H[b+28>>2]=(a.getTime()-c.getTime())/864E5|0;H[b+36>>2]=-(60*a.getTimezoneOffset());var d=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();c=c.getTimezoneOffset();a=(d!=c&&a.getTimezoneOffset()==
Math.min(c,d))|0;H[b+32>>2]=a;a=H[Z()+(a?4:0)>>2];H[b+40>>2]=a;return b},h:function(a){var b=Date.now()/1E3|0;a&&(H[a>>2]=b);return b},i:Hb,q:function(){A("missing function: wrenInitConfiguration");z(-1)},j:function(){A("missing function: wrenInterpret");z(-1)},p:function(){A("missing function: wrenNewVM");z(-1)}};
(function(){function a(e){f.asm=e.exports;la=f.asm.r;xa=e=la.buffer;f.HEAP8=F=new Int8Array(e);f.HEAP16=ya=new Int16Array(e);f.HEAP32=H=new Int32Array(e);f.HEAPU8=E=new Uint8Array(e);f.HEAPU16=new Uint16Array(e);f.HEAPU32=new Uint32Array(e);f.HEAPF32=new Float32Array(e);f.HEAPF64=new Float64Array(e);za=f.asm.u;Ba.unshift(f.asm.s);J--;f.monitorRunDependencies&&f.monitorRunDependencies(J);0==J&&(null!==Fa&&(clearInterval(Fa),Fa=null),K&&(e=K,K=null,e()))}function b(e){a(e.instance)}function c(e){return Ka().then(function(g){return WebAssembly.instantiate(g,
d)}).then(e,function(g){A("failed to asynchronously prepare wasm: "+g);z(g)})}var d={a:Kb};J++;f.monitorRunDependencies&&f.monitorRunDependencies(J);if(f.instantiateWasm)try{return f.instantiateWasm(d,a)}catch(e){return A("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return C||"function"!==typeof WebAssembly.instantiateStreaming||Ga()||L.startsWith("file://")||"function"!==typeof fetch?c(b):fetch(L,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,
d).then(b,function(g){A("wasm streaming compile failed: "+g);A("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();f.___wasm_call_ctors=function(){return(f.___wasm_call_ctors=f.asm.s).apply(null,arguments)};f._main=function(){return(f._main=f.asm.t).apply(null,arguments)};
var Ib=f.___errno_location=function(){return(Ib=f.___errno_location=f.asm.v).apply(null,arguments)},va=f._malloc=function(){return(va=f._malloc=f.asm.w).apply(null,arguments)},Z=f.__get_tzname=function(){return(Z=f.__get_tzname=f.asm.x).apply(null,arguments)},Gb=f.__get_daylight=function(){return(Gb=f.__get_daylight=f.asm.y).apply(null,arguments)},Fb=f.__get_timezone=function(){return(Fb=f.__get_timezone=f.asm.z).apply(null,arguments)},qa=f.stackSave=function(){return(qa=f.stackSave=f.asm.A).apply(null,
arguments)},ra=f.stackRestore=function(){return(ra=f.stackRestore=f.asm.B).apply(null,arguments)},D=f.stackAlloc=function(){return(D=f.stackAlloc=f.asm.C).apply(null,arguments)};f.cwrap=function(a,b,c,d){c=c||[];var e=c.every(function(g){return"number"===g});return"string"!==b&&e&&!d?na(a):function(){return oa(a,b,c,arguments)}};var Lb;function ja(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}K=function Mb(){Lb||Nb();Lb||(K=Mb)};
function Nb(a){function b(){if(!Lb&&(Lb=!0,f.calledRun=!0,!ma)){f.noFSInit||zb||(zb=!0,yb(),f.stdin=f.stdin,f.stdout=f.stdout,f.stderr=f.stderr,f.stdin?V("stdin",f.stdin):vb("/dev/tty","/dev/stdin"),f.stdout?V("stdout",null,f.stdout):vb("/dev/tty","/dev/stdout"),f.stderr?V("stderr",null,f.stderr):vb("/dev/tty1","/dev/stderr"),U("/dev/stdin",0),U("/dev/stdout",1),U("/dev/stderr",1));Ma(Ba);fb=!1;Ma(Ca);if(f.onRuntimeInitialized)f.onRuntimeInitialized();if(Ob){var c=a,d=f._main;c=c||[];var e=c.length+
1,g=D(4*(e+1));H[g>>2]=wa(aa);for(var k=1;k<e;k++)H[(g>>2)+k]=wa(c[k-1]);H[(g>>2)+e]=0;try{var p=d(e,g);Jb(p,!0)}catch(q){q instanceof ja||"unwind"==q||((c=q)&&"object"===typeof q&&q.stack&&(c=[q,q.stack]),A("exception thrown: "+c),r(1,q))}finally{}}if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;)c=f.postRun.shift(),Da.unshift(c);Ma(Da)}}a=a||m;if(!(0<J)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)Ea();Ma(Aa);0<J||(f.setStatus?
(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);b()},1)):b())}}f.run=Nb;function Jb(a,b){if(!b||!noExitRuntime||0!==a){if(!noExitRuntime){if(f.onExit)f.onExit(a);ma=!0}r(a,new ja(a))}}if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var Ob=!0;f.noInitialRun&&(Ob=!1);Nb();
