
var g;g||(g=typeof Module !== 'undefined' ? Module : {});var k={},l;for(l in g)g.hasOwnProperty(l)&&(k[l]=g[l]);var q=[],aa="./this.program";function r(a,b){throw b;}var ba=!1,u=!1,v=!1,ca=!1;ba="object"===typeof window;u="function"===typeof importScripts;v="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;ca=!ba&&!v&&!u;var w="",da,ea,y,fa,ha;
if(v)w=u?require("path").dirname(w)+"/":__dirname+"/",da=function(a,b){fa||(fa=require("fs"));ha||(ha=require("path"));a=ha.normalize(a);return fa.readFileSync(a,b?null:"utf8")},y=function(a){a=da(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(aa=process.argv[1].replace(/\\/g,"/")),q=process.argv.slice(2),"undefined"!==typeof module&&(module.exports=g),process.on("uncaughtException",function(a){if(!(a instanceof ia))throw a;}),process.on("unhandledRejection",
A),r=function(a){process.exit(a)},g.inspect=function(){return"[Emscripten Module object]"};else if(ca)"undefined"!=typeof read&&(da=function(a){return read(a)}),y=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?q=scriptArgs:"undefined"!=typeof arguments&&(q=arguments),"function"===typeof quit&&(r=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&
(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(ba||u)u?w=self.location.href:"undefined"!==typeof document&&document.currentScript&&(w=document.currentScript.src),w=0!==w.indexOf("blob:")?w.substr(0,w.lastIndexOf("/")+1):"",da=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},u&&(y=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),
ea=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var ja=g.print||console.log.bind(console),B=g.printErr||console.warn.bind(console);for(l in k)k.hasOwnProperty(l)&&(g[l]=k[l]);k=null;g.arguments&&(q=g.arguments);g.thisProgram&&(aa=g.thisProgram);g.quit&&(r=g.quit);var la=0,ma;g.wasmBinary&&(ma=g.wasmBinary);var noExitRuntime=g.noExitRuntime||!0;
"object"!==typeof WebAssembly&&A("no native wasm support detected");var na,qa=!1;function assert(a,b){a||A("Assertion failed: "+b)}function ra(a){var b=g["_"+a];assert(b,"Cannot call unknown function "+a+", make sure it is exported");return b}
function sa(a,b,c,d){var e={string:function(p){var t=0;if(null!==p&&void 0!==p&&0!==p){var z=(p.length<<2)+1;t=ta(z);ua(p,va,t,z)}return t},array:function(p){var t=ta(p.length);C.set(p,t);return t}},f=ra(a),h=[];a=0;if(d)for(var m=0;m<d.length;m++){var n=e[c[m]];n?(0===a&&(a=wa()),h[m]=n(d[m])):h[m]=d[m]}c=f.apply(null,h);c=function(p){return"string"===b?D(p):"boolean"===b?!!p:p}(c);0!==a&&xa(a);return c}var ya="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function za(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&ya)return ya.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|h:(e&7)<<18|f<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function D(a){return a?za(va,a,void 0):""}
function ua(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var h=a.charCodeAt(f);if(55296<=h&&57343>=h){var m=a.charCodeAt(++f);h=65536+((h&1023)<<10)|m&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e}
function Aa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function Ba(a){var b=Aa(a)+1,c=Ca(b);c&&ua(a,C,c,b);return c}function Da(a){var b=Aa(a)+1,c=ta(b);ua(a,C,c,b);return c}var Ea,C,va,E,Fa,F,Ga,Ha=[],Ia=[],Ja=[],Ma=[];function Na(){var a=g.preRun.shift();Ha.unshift(a)}var G=0,Oa=null,Pa=null;g.preloadedImages={};g.preloadedAudios={};
function A(a){if(g.onAbort)g.onAbort(a);B(a);qa=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function Qa(){return H.startsWith("data:application/octet-stream;base64,")}var H="bumblestack.wasm";if(!Qa()){var Ra=H;H=g.locateFile?g.locateFile(Ra,w):w+Ra}function Sa(){var a=H;try{if(a==H&&ma)return new Uint8Array(ma);if(y)return y(a);throw"both async and sync fetching of the wasm failed";}catch(b){A(b)}}
function Ta(){if(!ma&&(ba||u)){if("function"===typeof fetch&&!H.startsWith("file://"))return fetch(H,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+H+"'";return a.arrayBuffer()}).catch(function(){return Sa()});if(ea)return new Promise(function(a,b){ea(H,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return Sa()})}var I,J;
function Ua(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(g);else{var c=b.ib;"number"===typeof c?void 0===b.Ga?Ga.get(c)():Ga.get(c)(b.Ga):c(void 0===b.Ga?null:b.Ga)}}}function Va(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(v)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){A("randomDevice")}}
function Wa(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function K(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Wa(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function Xa(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function Ya(a){if("/"===a)return"/";a=K(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function Za(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Wa(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var $a=[];function ab(a,b){$a[a]={input:[],output:[],ua:b};bb(a,cb)}
var cb={open:function(a){var b=$a[a.node.rdev];if(!b)throw new L(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.ua.flush(a.tty)},flush:function(a){a.tty.ua.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.ua.Qa)throw new L(60);for(var e=0,f=0;f<d;f++){try{var h=a.tty.ua.Qa(a.tty)}catch(m){throw new L(29);}if(void 0===h&&0===e)throw new L(6);if(null===h||void 0===h)break;e++;b[c+f]=h}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.ua.Ja)throw new L(60);
try{for(var e=0;e<d;e++)a.tty.ua.Ja(a.tty,b[c+e])}catch(f){throw new L(29);}d&&(a.node.timestamp=Date.now());return e}},db={Qa:function(a){if(!a.input.length){var b=null;if(v){var c=Buffer.Ya?Buffer.Ya(256):new Buffer(256),d=0;try{d=fa.readSync(process.stdin.fd,c,0,256,null)}catch(e){if(e.toString().includes("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==
typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;c=Array(Aa(b)+1);b=ua(b,c,0,c.length);c.length=b;a.input=c}return a.input.shift()},Ja:function(a,b){null===b||10===b?(ja(za(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(ja(za(a.output,0)),a.output=[])}},eb={Ja:function(a,b){null===b||10===b?(B(za(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(B(za(a.output,0)),a.output=[])}},
M={na:null,ma:function(){return M.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new L(63);M.na||(M.na={dir:{node:{la:M.aa.la,oa:M.aa.oa,lookup:M.aa.lookup,Ca:M.aa.Ca,rename:M.aa.rename,unlink:M.aa.unlink,rmdir:M.aa.rmdir,readdir:M.aa.readdir,symlink:M.aa.symlink},stream:{qa:M.ba.qa}},file:{node:{la:M.aa.la,oa:M.aa.oa},stream:{qa:M.ba.qa,read:M.ba.read,write:M.ba.write,Ma:M.ba.Ma,Ra:M.ba.Ra,Ta:M.ba.Ta}},link:{node:{la:M.aa.la,oa:M.aa.oa,readlink:M.aa.readlink},
stream:{}},Na:{node:{la:M.aa.la,oa:M.aa.oa},stream:fb}});c=gb(a,b,c,d);N(c.mode)?(c.aa=M.na.dir.node,c.ba=M.na.dir.stream,c.da={}):32768===(c.mode&61440)?(c.aa=M.na.file.node,c.ba=M.na.file.stream,c.fa=0,c.da=null):40960===(c.mode&61440)?(c.aa=M.na.link.node,c.ba=M.na.link.stream):8192===(c.mode&61440)&&(c.aa=M.na.Na.node,c.ba=M.na.Na.stream);c.timestamp=Date.now();a&&(a.da[b]=c,a.timestamp=c.timestamp);return c},jb:function(a){return a.da?a.da.subarray?a.da.subarray(0,a.fa):new Uint8Array(a.da):
new Uint8Array(0)},Oa:function(a,b){var c=a.da?a.da.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.da,a.da=new Uint8Array(b),0<a.fa&&a.da.set(c.subarray(0,a.fa),0))},cb:function(a,b){if(a.fa!=b)if(0==b)a.da=null,a.fa=0;else{var c=a.da;a.da=new Uint8Array(b);c&&a.da.set(c.subarray(0,Math.min(b,a.fa)));a.fa=b}},aa:{la:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;N(a.mode)?b.size=4096:32768===
(a.mode&61440)?b.size=a.fa:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Za=4096;b.blocks=Math.ceil(b.size/b.Za);return b},oa:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&M.cb(a,b.size)},lookup:function(){throw hb[44];},Ca:function(a,b,c,d){return M.createNode(a,b,c,d)},rename:function(a,b,c){if(N(a.mode)){try{var d=O(b,c)}catch(f){}if(d)for(var e in d.da)throw new L(55);
}delete a.parent.da[a.name];a.parent.timestamp=Date.now();a.name=c;b.da[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink:function(a,b){delete a.da[b];a.timestamp=Date.now()},rmdir:function(a,b){var c=O(a,b),d;for(d in c.da)throw new L(55);delete a.da[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.da)a.da.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=M.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new L(28);
return a.link}},ba:{read:function(a,b,c,d,e){var f=a.node.da;if(e>=a.node.fa)return 0;a=Math.min(a.node.fa-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.da||a.da.subarray)){if(f)return a.da=b.subarray(c,c+d),a.fa=d;if(0===a.fa&&0===e)return a.da=b.slice(c,c+d),a.fa=d;if(e+d<=a.fa)return a.da.set(b.subarray(c,c+d),e),d}M.Oa(a,e+d);if(a.da.subarray&&b.subarray)a.da.set(b.subarray(c,
c+d),e);else for(f=0;f<d;f++)a.da[e+f]=b[c+f];a.fa=Math.max(a.fa,e+d);return d},qa:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.fa);if(0>b)throw new L(28);return b},Ma:function(a,b,c){M.Oa(a.node,b+c);a.node.fa=Math.max(a.node.fa,b+c)},Ra:function(a,b,c,d,e,f){if(0!==b)throw new L(28);if(32768!==(a.node.mode&61440))throw new L(43);a=a.node.da;if(f&2||a.buffer!==Ea){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;
f=65536*Math.ceil(c/65536);for(b=Ca(f);c<f;)C[b+c++]=0;c=b;if(!c)throw new L(48);C.set(a,c)}else d=!1,c=a.byteOffset;return{mb:c,gb:d}},Ta:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new L(43);if(e&2)return 0;M.ba.write(a,b,0,d,c,!1);return 0}}},ib=null,jb={},P=[],kb=1,Q=null,lb=!0,R={},L=null,hb={};
function S(a,b){a=Za("/",a);b=b||{};if(!a)return{path:"",node:null};var c={Pa:!0,Ka:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.Ka)throw new L(32);a=Wa(a.split("/").filter(function(h){return!!h}),!1);var e=ib;c="/";for(d=0;d<a.length;d++){var f=d===a.length-1;if(f&&b.parent)break;e=O(e,a[d]);c=K(c+"/"+a[d]);e.sa&&(!f||f&&b.Pa)&&(e=e.sa.root);if(!f||b.Ha)for(f=0;40960===(e.mode&61440);)if(e=mb(c),c=Za(Xa(c),e),e=S(c,{Ka:b.Ka}).node,40<f++)throw new L(32);}return{path:c,node:e}}
function nb(a){for(var b;;){if(a===a.parent)return a=a.ma.Sa,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function ob(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Q.length}function pb(a){var b=ob(a.parent.id,a.name);if(Q[b]===a)Q[b]=a.ta;else for(b=Q[b];b;){if(b.ta===a){b.ta=a.ta;break}b=b.ta}}
function O(a,b){var c;if(c=(c=qb(a,"x"))?c:a.aa.lookup?0:2)throw new L(c,a);for(c=Q[ob(a.id,b)];c;c=c.ta){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.aa.lookup(a,b)}function gb(a,b,c,d){a=new rb(a,b,c,d);b=ob(a.parent.id,a.name);a.ta=Q[b];return Q[b]=a}function N(a){return 16384===(a&61440)}var sb={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090};function tb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}
function qb(a,b){if(lb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function ub(a,b){try{return O(a,b),20}catch(c){}return qb(a,"wx")}function vb(a,b,c){try{var d=O(a,b)}catch(e){return e.ea}if(a=qb(a,"wx"))return a;if(c){if(!N(d.mode))return 54;if(d===d.parent||"/"===nb(d))return 10}else if(N(d.mode))return 31;return 0}function wb(a,b){b=b||4096;for(a=a||0;a<=b;a++)if(!P[a])return a;throw new L(33);}
function xb(a,b,c){yb||(yb=function(){},yb.prototype={});var d=new yb,e;for(e in a)d[e]=a[e];a=d;b=wb(b,c);a.fd=b;return P[b]=a}var fb={open:function(a){a.ba=jb[a.node.rdev].ba;a.ba.open&&a.ba.open(a)},qa:function(){throw new L(70);}};function bb(a,b){jb[a]={ba:b}}
function zb(a,b){var c="/"===b,d=!b;if(c&&ib)throw new L(10);if(!c&&!d){var e=S(b,{Pa:!1});b=e.path;e=e.node;if(e.sa)throw new L(10);if(!N(e.mode))throw new L(54);}b={type:a,lb:{},Sa:b,bb:[]};a=a.ma(b);a.ma=b;b.root=a;c?ib=a:e&&(e.sa=b,e.ma&&e.ma.bb.push(b));return a}function Ab(a,b,c){var d=S(a,{parent:!0}).node;a=Ya(a);if(!a||"."===a||".."===a)throw new L(28);var e=ub(d,a);if(e)throw new L(e);if(!d.aa.Ca)throw new L(63);return d.aa.Ca(d,a,b,c)}function T(a){return Ab(a,16895,0)}
function Bb(a,b,c){"undefined"===typeof c&&(c=b,b=438);Ab(a,b|8192,c)}function Cb(a,b){if(!Za(a))throw new L(44);var c=S(b,{parent:!0}).node;if(!c)throw new L(44);b=Ya(b);var d=ub(c,b);if(d)throw new L(d);if(!c.aa.symlink)throw new L(63);c.aa.symlink(c,b,a)}function mb(a){a=S(a).node;if(!a)throw new L(44);if(!a.aa.readlink)throw new L(28);return Za(nb(a.parent),a.aa.readlink(a))}
function Db(a,b,c,d){if(""===a)throw new L(44);if("string"===typeof b){var e=sb[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var f=a;else{a=K(a);try{f=S(a,{Ha:!(b&131072)}).node}catch(h){}}e=!1;if(b&64)if(f){if(b&128)throw new L(20);}else f=Ab(a,c,0),e=!0;if(!f)throw new L(44);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&!N(f.mode))throw new L(54);if(!e&&(c=f?40960===(f.mode&61440)?32:N(f.mode)&&
("r"!==tb(b)||b&512)?31:qb(f,tb(b)):44))throw new L(c);if(b&512){c=f;c="string"===typeof c?S(c,{Ha:!0}).node:c;if(!c.aa.oa)throw new L(63);if(N(c.mode))throw new L(31);if(32768!==(c.mode&61440))throw new L(28);if(e=qb(c,"w"))throw new L(e);c.aa.oa(c,{size:0,timestamp:Date.now()})}b&=-131713;d=xb({node:f,path:nb(f),flags:b,seekable:!0,position:0,ba:f.ba,fb:[],error:!1},d,void 0);d.ba.open&&d.ba.open(d);!g.logReadFiles||b&1||(Eb||(Eb={}),a in Eb||(Eb[a]=1,B("FS.trackingDelegate error on read file: "+
a)));try{R.onOpenFile&&(f=0,1!==(b&2097155)&&(f|=1),0!==(b&2097155)&&(f|=2),R.onOpenFile(a,f))}catch(h){B("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+h.message)}return d}function Fb(a,b,c){if(null===a.fd)throw new L(8);if(!a.seekable||!a.ba.qa)throw new L(70);if(0!=c&&1!=c&&2!=c)throw new L(28);a.position=a.ba.qa(a,b,c);a.fb=[]}
function Gb(a,b,c,d){var e=C;if(0>c||0>d)throw new L(28);if(null===a.fd)throw new L(8);if(0===(a.flags&2097155))throw new L(8);if(N(a.node.mode))throw new L(31);if(!a.ba.write)throw new L(28);a.seekable&&a.flags&1024&&Fb(a,0,2);var f="undefined"!==typeof d;if(!f)d=a.position;else if(!a.seekable)throw new L(70);b=a.ba.write(a,e,b,c,d,void 0);f||(a.position+=b);try{if(a.path&&R.onWriteToFile)R.onWriteToFile(a.path)}catch(h){B("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+
h.message)}return b}function Hb(){L||(L=function(a,b){this.node=b;this.eb=function(c){this.ea=c};this.eb(a);this.message="FS error"},L.prototype=Error(),L.prototype.constructor=L,[44].forEach(function(a){hb[a]=new L(a);hb[a].stack="<generic error, no stack>"}))}var Ib;function Jb(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function Kb(a,b,c){a=K("/dev/"+a);var d=Jb(!!b,!!c);Lb||(Lb=64);var e=Lb++<<8|0;bb(e,{open:function(f){f.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(f,h,m,n){for(var p=0,t=0;t<n;t++){try{var z=b()}catch(ka){throw new L(29);}if(void 0===z&&0===p)throw new L(6);if(null===z||void 0===z)break;p++;h[m+t]=z}p&&(f.node.timestamp=Date.now());return p},write:function(f,h,m,n){for(var p=0;p<n;p++)try{c(h[m+p])}catch(t){throw new L(29);}n&&(f.node.timestamp=Date.now());return p}});
Bb(a,d,e)}
var Lb,U={},yb,Eb,V={ma:function(){g.websocket=g.websocket&&"object"===typeof g.websocket?g.websocket:{};g.websocket.Fa={};g.websocket.on=function(a,b){"function"===typeof b&&(this.Fa[a]=b);return this};g.websocket.emit=function(a,b){"function"===typeof this.Fa[a]&&this.Fa[a].call(this,b)};return gb(null,"/",16895,0)},createSocket:function(a,b,c){b&=-526337;c&&assert(1==b==(6==c));a={family:a,type:b,protocol:c,ga:null,error:null,xa:{},pending:[],va:[],pa:V.ia};b=V.Da();c=gb(V.root,b,49152,0);c.wa=
a;b=xb({path:b,node:c,flags:2,seekable:!1,ba:V.ba});a.stream=b;return a},$a:function(a){return(a=P[a])&&49152===(a.node.mode&49152)?a.node.wa:null},ba:{Ua:function(a){a=a.node.wa;return a.pa.Ua(a)},Ba:function(a,b,c){a=a.node.wa;return a.pa.Ba(a,b,c)},read:function(a,b,c,d){a=a.node.wa;d=a.pa.Va(a,d);if(!d)return 0;b.set(d.buffer,c);return d.buffer.length},write:function(a,b,c,d){a=a.node.wa;return a.pa.Xa(a,b,c,d)},close:function(a){a=a.node.wa;a.pa.close(a)}},Da:function(){V.Da.current||(V.Da.current=
0);return"socket["+V.Da.current++ +"]"},ia:{ya:function(a,b,c){if("object"===typeof b){var d=b;c=b=null}if(d)if(d._socket)b=d._socket.remoteAddress,c=d._socket.remotePort;else{c=/ws[s]?:\/\/([^:]+):(\d+)/.exec(d.url);if(!c)throw Error("WebSocket URL must be in the format ws(s)://address:port");b=c[1];c=parseInt(c[2],10)}else try{var e=g.websocket&&"object"===typeof g.websocket,f="ws:#".replace("#","//");e&&"string"===typeof g.websocket.url&&(f=g.websocket.url);if("ws://"===f||"wss://"===f){var h=
b.split("/");f=f+h[0]+":"+c+"/"+h.slice(1).join("/")}h="binary";e&&"string"===typeof g.websocket.subprotocol&&(h=g.websocket.subprotocol);var m=void 0;"null"!==h&&(h=h.replace(/^ +| +$/g,"").split(/ *, */),m=v?{protocol:h.toString()}:h);e&&null===g.websocket.subprotocol&&(m=void 0);d=new (v?require("ws"):WebSocket)(f,m);d.binaryType="arraybuffer"}catch(n){throw new L(23);}b={ha:b,port:c,socket:d,za:[]};V.ia.La(a,b);V.ia.ab(a,b);2===a.type&&"undefined"!==typeof a.ra&&b.za.push(new Uint8Array([255,
255,255,255,112,111,114,116,(a.ra&65280)>>8,a.ra&255]));return b},Aa:function(a,b,c){return a.xa[b+":"+c]},La:function(a,b){a.xa[b.ha+":"+b.port]=b},Wa:function(a,b){delete a.xa[b.ha+":"+b.port]},ab:function(a,b){function c(){g.websocket.emit("open",a.stream.fd);try{for(var f=b.za.shift();f;)b.socket.send(f),f=b.za.shift()}catch(h){b.socket.close()}}function d(f){if("string"===typeof f)f=(new TextEncoder).encode(f);else{assert(void 0!==f.byteLength);if(0==f.byteLength)return;f=new Uint8Array(f)}var h=
e;e=!1;h&&10===f.length&&255===f[0]&&255===f[1]&&255===f[2]&&255===f[3]&&112===f[4]&&111===f[5]&&114===f[6]&&116===f[7]?(f=f[8]<<8|f[9],V.ia.Wa(a,b),b.port=f,V.ia.La(a,b)):(a.va.push({ha:b.ha,port:b.port,data:f}),g.websocket.emit("message",a.stream.fd))}var e=!0;v?(b.socket.on("open",c),b.socket.on("message",function(f,h){h.hb&&d((new Uint8Array(f)).buffer)}),b.socket.on("close",function(){g.websocket.emit("close",a.stream.fd)}),b.socket.on("error",function(){a.error=14;g.websocket.emit("error",[a.stream.fd,
a.error,"ECONNREFUSED: Connection refused"])})):(b.socket.onopen=c,b.socket.onclose=function(){g.websocket.emit("close",a.stream.fd)},b.socket.onmessage=function(f){d(f.data)},b.socket.onerror=function(){a.error=14;g.websocket.emit("error",[a.stream.fd,a.error,"ECONNREFUSED: Connection refused"])})},Ua:function(a){if(1===a.type&&a.ga)return a.pending.length?65:0;var b=0,c=1===a.type?V.ia.Aa(a,a.ja,a.ka):null;if(a.va.length||!c||c&&c.socket.readyState===c.socket.CLOSING||c&&c.socket.readyState===c.socket.CLOSED)b|=
65;if(!c||c&&c.socket.readyState===c.socket.OPEN)b|=4;if(c&&c.socket.readyState===c.socket.CLOSING||c&&c.socket.readyState===c.socket.CLOSED)b|=16;return b},Ba:function(a,b,c){switch(b){case 21531:return b=0,a.va.length&&(b=a.va[0].data.length),F[c>>2]=b,0;default:return 28}},close:function(a){if(a.ga){try{a.ga.close()}catch(e){}a.ga=null}for(var b=Object.keys(a.xa),c=0;c<b.length;c++){var d=a.xa[b[c]];try{d.socket.close()}catch(e){}V.ia.Wa(a,d)}return 0},bind:function(a,b,c){if("undefined"!==typeof a.Ea||
"undefined"!==typeof a.ra)throw new L(28);a.Ea=b;a.ra=c;if(2===a.type){a.ga&&(a.ga.close(),a.ga=null);try{a.pa.listen(a,0)}catch(d){if(!(d instanceof L))throw d;if(138!==d.ea)throw d;}}},connect:function(a,b,c){if(a.ga)throw new L(138);if("undefined"!==typeof a.ja&&"undefined"!==typeof a.ka){var d=V.ia.Aa(a,a.ja,a.ka);if(d){if(d.socket.readyState===d.socket.CONNECTING)throw new L(7);throw new L(30);}}b=V.ia.ya(a,b,c);a.ja=b.ha;a.ka=b.port;throw new L(26);},listen:function(a){if(!v)throw new L(138);
if(a.ga)throw new L(28);var b=require("ws").Server;a.ga=new b({host:a.Ea,port:a.ra});g.websocket.emit("listen",a.stream.fd);a.ga.on("connection",function(c){if(1===a.type){var d=V.createSocket(a.family,a.type,a.protocol);c=V.ia.ya(d,c);d.ja=c.ha;d.ka=c.port;a.pending.push(d);g.websocket.emit("connection",d.stream.fd)}else V.ia.ya(a,c),g.websocket.emit("connection",a.stream.fd)});a.ga.on("closed",function(){g.websocket.emit("close",a.stream.fd);a.ga=null});a.ga.on("error",function(){a.error=23;g.websocket.emit("error",
[a.stream.fd,a.error,"EHOSTUNREACH: Host is unreachable"])})},accept:function(a){if(!a.ga)throw new L(28);var b=a.pending.shift();b.stream.flags=a.stream.flags;return b},kb:function(a,b){if(b){if(void 0===a.ja||void 0===a.ka)throw new L(53);b=a.ja;a=a.ka}else b=a.Ea||0,a=a.ra||0;return{ha:b,port:a}},Xa:function(a,b,c,d,e,f){if(2===a.type){if(void 0===e||void 0===f)e=a.ja,f=a.ka;if(void 0===e||void 0===f)throw new L(17);}else e=a.ja,f=a.ka;var h=V.ia.Aa(a,e,f);if(1===a.type){if(!h||h.socket.readyState===
h.socket.CLOSING||h.socket.readyState===h.socket.CLOSED)throw new L(53);if(h.socket.readyState===h.socket.CONNECTING)throw new L(6);}ArrayBuffer.isView(b)&&(c+=b.byteOffset,b=b.buffer);b=b.slice(c,c+d);if(2===a.type&&(!h||h.socket.readyState!==h.socket.OPEN))return h&&h.socket.readyState!==h.socket.CLOSING&&h.socket.readyState!==h.socket.CLOSED||(h=V.ia.ya(a,e,f)),h.za.push(b),d;try{return h.socket.send(b),d}catch(m){throw new L(28);}},Va:function(a,b){if(1===a.type&&a.ga)throw new L(53);var c=a.va.shift();
if(!c){if(1===a.type){if(a=V.ia.Aa(a,a.ja,a.ka)){if(a.socket.readyState===a.socket.CLOSING||a.socket.readyState===a.socket.CLOSED)return null;throw new L(6);}throw new L(53);}throw new L(6);}var d=c.data.byteLength||c.data.length,e=c.data.byteOffset||0,f=c.data.buffer||c.data;b=Math.min(b,d);var h={buffer:new Uint8Array(f,e,b),ha:c.ha,port:c.port};1===a.type&&b<d&&(c.data=new Uint8Array(f,e+b,d-b),a.va.unshift(c));return h}}};function W(a){a=V.$a(a);if(!a)throw new L(8);return a}
function Mb(a){a=a.split(".");for(var b=0;4>b;b++){var c=Number(a[b]);if(isNaN(c))return null;a[b]=c}return(a[0]|a[1]<<8|a[2]<<16|a[3]<<24)>>>0}
function Nb(a){var b,c,d=[];if(!/^((?=.*::)(?!.*::.+::)(::)?([\dA-F]{1,4}:(:|\b)|){5}|([\dA-F]{1,4}:){6})((([\dA-F]{1,4}((?!\3)::|:\b|$))|(?!\2\3)){2}|(((2[0-4]|1\d|[1-9])?\d|25[0-5])\.?\b){4})$/i.test(a))return null;if("::"===a)return[0,0,0,0,0,0,0,0];a=a.startsWith("::")?a.replace("::","Z:"):a.replace("::",":Z:");0<a.indexOf(".")?(a=a.replace(/[.]/g,":"),a=a.split(":"),a[a.length-4]=parseInt(a[a.length-4])+256*parseInt(a[a.length-3]),a[a.length-3]=parseInt(a[a.length-2])+256*parseInt(a[a.length-
1]),a=a.slice(0,a.length-2)):a=a.split(":");for(b=c=0;b<a.length;b++)if("string"===typeof a[b])if("Z"===a[b]){for(c=0;c<8-a.length+1;c++)d[b+c]=0;--c}else d[b+c]=Ob(parseInt(a[b],16));else d[b+c]=a[b];return[d[1]<<16|d[0],d[3]<<16|d[2],d[5]<<16|d[4],d[7]<<16|d[6]]}
function Pb(a,b,c,d,e){switch(b){case 2:c=Mb(c);e&&(F[e>>2]=16);E[a>>1]=b;F[a+4>>2]=c;E[a+2>>1]=Ob(d);J=[0,(I=0,1<=+Math.abs(I)?0<I?(Math.min(+Math.floor(I/4294967296),4294967295)|0)>>>0:~~+Math.ceil((I-+(~~I>>>0))/4294967296)>>>0:0)];F[a+8>>2]=J[0];F[a+12>>2]=J[1];break;case 10:c=Nb(c);e&&(F[e>>2]=28);F[a>>2]=b;F[a+8>>2]=c[0];F[a+12>>2]=c[1];F[a+16>>2]=c[2];F[a+20>>2]=c[3];E[a+2>>1]=Ob(d);F[a+4>>2]=0;F[a+24>>2]=0;break;default:return 5}return 0}var Qb=1,Rb={},Sb={};
function Tb(a){var b=Mb(a);if(null!==b)return a;b=Nb(a);if(null!==b)return a;Rb[a]?b=Rb[a]:(b=Qb++,assert(65535>b,"exceeded max address mappings of 65535"),b="172.29."+(b&255)+"."+(b&65280),Sb[b]=a,Rb[a]=b);return b}var Ub=void 0;function X(){Ub+=4;return F[Ub-4>>2]}function Y(a){a=P[a];if(!a)throw new L(8);return a}function Vb(a){return(a&255)+"."+(a>>8&255)+"."+(a>>16&255)+"."+(a>>24&255)}
function Wb(a){var b="",c,d=0,e=0,f=0,h=0;a=[a[0]&65535,a[0]>>16,a[1]&65535,a[1]>>16,a[2]&65535,a[2]>>16,a[3]&65535,a[3]>>16];var m=!0;for(c=0;5>c;c++)if(0!==a[c]){m=!1;break}if(m){c=Vb(a[6]|a[7]<<16);if(-1===a[5])return"::ffff:"+c;if(0===a[5])return"0.0.0.0"===c&&(c=""),"0.0.0.1"===c&&(c="1"),"::"+c}for(c=0;8>c;c++)0===a[c]&&(1<c-e&&(h=0),e=c,h++),h>d&&(d=h,f=c-d+1);for(c=0;8>c;c++)1<d&&0===a[c]&&c>=f&&c<f+d?c===f&&(b+=":",0===f&&(b+=":")):(b+=Number(Xb(a[c]&65535)).toString(16),b+=7>c?":":"");return b}
function Yb(a,b){var c=E[a>>1],d=Xb(Fa[a+2>>1]);switch(c){case 2:if(16!==b)return{ea:28};a=F[a+4>>2];a=Vb(a);break;case 10:if(28!==b)return{ea:28};a=[F[a+8>>2],F[a+12>>2],F[a+16>>2],F[a+20>>2]];a=Wb(a);break;default:return{ea:5}}return{family:c,ha:a,port:d}}function Zb(){void 0===Zb.start&&(Zb.start=Date.now());return 1E3*(Date.now()-Zb.start)|0}var $b={};
function ac(){if(!bc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:aa||"./this.program"},b;for(b in $b)a[b]=$b[b];var c=[];for(b in a)c.push(b+"="+a[b]);bc=c}return bc}var bc;
function cc(){function a(h){return(h=h.toTimeString().match(/\(([A-Za-z ]+)\)$/))?h[1]:"GMT"}if(!dc){dc=!0;var b=(new Date).getFullYear(),c=new Date(b,0,1),d=new Date(b,6,1);b=c.getTimezoneOffset();var e=d.getTimezoneOffset(),f=Math.max(b,e);F[ec()>>2]=60*f;F[fc()>>2]=Number(b!=e);c=a(c);d=a(d);c=Ba(c);d=Ba(d);e<b?(F[Z()>>2]=c,F[Z()+4>>2]=d):(F[Z()>>2]=d,F[Z()+4>>2]=c)}}var dc;
function rb(a,b,c,d){a||(a=this);this.parent=a;this.ma=a.ma;this.sa=null;this.id=kb++;this.name=b;this.mode=c;this.aa={};this.ba={};this.rdev=d}Object.defineProperties(rb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});Hb();Q=Array(4096);zb(M,"/");T("/tmp");T("/home");T("/home/web_user");
(function(){T("/dev");bb(259,{read:function(){return 0},write:function(b,c,d,e){return e}});Bb("/dev/null",259);ab(1280,db);ab(1536,eb);Bb("/dev/tty",1280);Bb("/dev/tty1",1536);var a=Va();Kb("random",a);Kb("urandom",a);T("/dev/shm");T("/dev/shm/tmp")})();
(function(){T("/proc");var a=T("/proc/self");T("/proc/self/fd");zb({ma:function(){var b=gb(a,"fd",16895,73);b.aa={lookup:function(c,d){var e=P[+d];if(!e)throw new L(8);c={parent:null,ma:{Sa:"fake"},aa:{readlink:function(){return e.path}}};return c.parent=c}};return b}},"/proc/self/fd")})();
var nc={L:function(){B("missing function: Jim_InitStaticExtensions");A(-1)},d:function(a,b,c,d){A("Assertion failed: "+D(a)+", at: "+[b?D(b):"unknown filename",c,d?D(d):"unknown function"])},w:function(a,b,c){try{var d=W(a),e=d.pa.accept(d);b&&Pb(b,e.family,Tb(e.ja),e.ka,c);return e.stream.fd}catch(f){return"undefined"!==typeof U&&f instanceof L||A(f),-f.ea}},a:function(a,b,c){Ub=c;try{var d=Y(a);switch(b){case 0:var e=X();return 0>e?-28:Db(d.path,d.flags,0,e).fd;case 1:case 2:return 0;case 3:return d.flags;
case 4:return e=X(),d.flags|=e,0;case 12:return e=X(),E[e+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return F[hc()>>2]=28,-1;default:return-28}}catch(f){return"undefined"!==typeof U&&f instanceof L||A(f),-f.ea}},u:function(a,b,c){try{var d=W(a);if(!d.ja)return-53;Pb(b,d.family,Tb(d.ja),d.ka,c);return 0}catch(e){return"undefined"!==typeof U&&e instanceof L||A(e),-e.ea}},v:function(a,b,c){try{B("__sys_getsockname "+a);var d=W(a);Pb(b,d.family,Tb(d.Ea||"0.0.0.0"),d.ra,c);return 0}catch(e){return"undefined"!==
typeof U&&e instanceof L||A(e),-e.ea}},r:function(a,b,c,d,e){try{var f=W(a);return 1===b&&4===c?(F[d>>2]=f.error,F[e>>2]=4,f.error=null,0):-50}catch(h){return"undefined"!==typeof U&&h instanceof L||A(h),-h.ea}},l:function(a,b,c){Ub=c;try{var d=Y(a);switch(b){case 21509:case 21505:return d.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.tty?0:-59;case 21519:if(!d.tty)return-59;var e=X();return F[e>>2]=0;case 21520:return d.tty?-28:-59;case 21531:a=e=X();if(!d.ba.Ba)throw new L(59);
return d.ba.Ba(d,b,a);case 21523:return d.tty?0:-59;case 21524:return d.tty?0:-59;default:A("bad ioctl syscall "+b)}}catch(f){return"undefined"!==typeof U&&f instanceof L||A(f),-f.ea}},y:function(a,b){try{var c=W(a);c.pa.listen(c,b);return 0}catch(d){return"undefined"!==typeof U&&d instanceof L||A(d),-d.ea}},J:function(a,b,c){Ub=c;try{var d=D(a),e=c?X():0;return Db(d,b,e).fd}catch(f){return"undefined"!==typeof U&&f instanceof L||A(f),-f.ea}},s:function(a,b,c,d,e,f){try{var h=W(a),m=h.pa.Va(h,c);if(!m)return 0;
e&&Pb(e,h.family,Tb(m.ha),m.port,f);va.set(m.buffer,b);return m.buffer.byteLength}catch(n){return"undefined"!==typeof U&&n instanceof L||A(n),-n.ea}},H:function(a){try{a=D(a);var b=S(a,{parent:!0}).node,c=Ya(a),d=O(b,c),e=vb(b,c,!0);if(e)throw new L(e);if(!b.aa.rmdir)throw new L(63);if(d.sa)throw new L(10);try{R.willDeletePath&&R.willDeletePath(a)}catch(f){B("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+f.message)}b.aa.rmdir(b,c);pb(d);try{if(R.onDeletePath)R.onDeletePath(a)}catch(f){B("FS.trackingDelegate['onDeletePath']('"+
a+"') threw an exception: "+f.message)}return 0}catch(f){return"undefined"!==typeof U&&f instanceof L||A(f),-f.ea}},t:function(a,b,c,d,e,f){try{var h=W(a);if(0===e)var m=null;else{var n=Yb(e,f);if(n.ea)throw new L(n.ea);var p=n.ha;n.ha=(Sb[p]?Sb[p]:null)||n.ha;m=n}return m?h.pa.Xa(h,C,b,c,m.ha,m.port):Gb(h.stream,b,c)}catch(t){return"undefined"!==typeof U&&t instanceof L||A(t),-t.ea}},q:function(){return-50},z:function(a){try{return W(a),-52}catch(b){return"undefined"!==typeof U&&b instanceof L||
A(b),-b.ea}},D:function(a,b){try{a=D(a);a:{try{var c=S(a,{Ha:!0}).node;if(!c)throw new L(44);if(!c.aa.la)throw new L(63);var d=c.aa.la(c)}catch(f){if(f&&f.node&&K(a)!==K(nb(f.node))){var e=-54;break a}throw f;}F[b>>2]=d.dev;F[b+4>>2]=0;F[b+8>>2]=d.ino;F[b+12>>2]=d.mode;F[b+16>>2]=d.nlink;F[b+20>>2]=d.uid;F[b+24>>2]=d.gid;F[b+28>>2]=d.rdev;F[b+32>>2]=0;J=[d.size>>>0,(I=d.size,1<=+Math.abs(I)?0<I?(Math.min(+Math.floor(I/4294967296),4294967295)|0)>>>0:~~+Math.ceil((I-+(~~I>>>0))/4294967296)>>>0:0)];
F[b+40>>2]=J[0];F[b+44>>2]=J[1];F[b+48>>2]=4096;F[b+52>>2]=d.blocks;F[b+56>>2]=d.atime.getTime()/1E3|0;F[b+60>>2]=0;F[b+64>>2]=d.mtime.getTime()/1E3|0;F[b+68>>2]=0;F[b+72>>2]=d.ctime.getTime()/1E3|0;F[b+76>>2]=0;J=[d.ino>>>0,(I=d.ino,1<=+Math.abs(I)?0<I?(Math.min(+Math.floor(I/4294967296),4294967295)|0)>>>0:~~+Math.ceil((I-+(~~I>>>0))/4294967296)>>>0:0)];F[b+80>>2]=J[0];F[b+84>>2]=J[1];e=0}return e}catch(f){return"undefined"!==typeof U&&f instanceof L||A(f),-f.ea}},I:function(a){try{a=D(a);var b=
S(a,{parent:!0}).node,c=Ya(a),d=O(b,c),e=vb(b,c,!1);if(e)throw new L(e);if(!b.aa.unlink)throw new L(63);if(d.sa)throw new L(10);try{R.willDeletePath&&R.willDeletePath(a)}catch(f){B("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+f.message)}b.aa.unlink(b,c);pb(d);try{if(R.onDeletePath)R.onDeletePath(a)}catch(f){B("FS.trackingDelegate['onDeletePath']('"+a+"') threw an exception: "+f.message)}return 0}catch(f){return"undefined"!==typeof U&&f instanceof L||A(f),-f.ea}},g:function(){A()},
n:Zb,c:function(a,b){ic(a,b||1);throw"longjmp";},A:function(){A("OOM")},B:function(a,b){try{var c=0;ac().forEach(function(d,e){var f=b+c;e=F[a+4*e>>2]=f;for(f=0;f<d.length;++f)C[e++>>0]=d.charCodeAt(f);C[e>>0]=0;c+=d.length+1});return 0}catch(d){return"undefined"!==typeof U&&d instanceof L||A(d),d.ea}},C:function(a,b){try{var c=ac();F[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});F[b>>2]=d;return 0}catch(e){return"undefined"!==typeof U&&e instanceof L||A(e),e.ea}},e:function(a){jc(a)},
h:function(a){try{var b=Y(a);if(null===b.fd)throw new L(8);b.Ia&&(b.Ia=null);try{b.ba.close&&b.ba.close(b)}catch(c){throw c;}finally{P[b.fd]=null}b.fd=null;return 0}catch(c){return"undefined"!==typeof U&&c instanceof L||A(c),c.ea}},E:function(a,b){try{var c=Y(a);C[b>>0]=c.tty?2:N(c.mode)?3:40960===(c.mode&61440)?7:4;return 0}catch(d){return"undefined"!==typeof U&&d instanceof L||A(d),d.ea}},G:function(a,b,c,d){try{a:{for(var e=Y(a),f=a=0;f<c;f++){var h=F[b+(8*f+4)>>2],m=e,n=F[b+8*f>>2],p=h,t=void 0,
z=C;if(0>p||0>t)throw new L(28);if(null===m.fd)throw new L(8);if(1===(m.flags&2097155))throw new L(8);if(N(m.node.mode))throw new L(31);if(!m.ba.read)throw new L(28);var ka="undefined"!==typeof t;if(!ka)t=m.position;else if(!m.seekable)throw new L(70);var Ka=m.ba.read(m,z,n,p,t);ka||(m.position+=Ka);var oa=Ka;if(0>oa){var x=-1;break a}a+=oa;if(oa<h)break}x=a}F[d>>2]=x;return 0}catch(pa){return"undefined"!==typeof U&&pa instanceof L||A(pa),pa.ea}},p:function(a,b,c,d,e){try{var f=Y(a);a=4294967296*
c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;Fb(f,a,d);J=[f.position>>>0,(I=f.position,1<=+Math.abs(I)?0<I?(Math.min(+Math.floor(I/4294967296),4294967295)|0)>>>0:~~+Math.ceil((I-+(~~I>>>0))/4294967296)>>>0:0)];F[e>>2]=J[0];F[e+4>>2]=J[1];f.Ia&&0===a&&0===d&&(f.Ia=null);return 0}catch(h){return"undefined"!==typeof U&&h instanceof L||A(h),h.ea}},F:function(a){try{var b=Y(a);return b.ba&&b.ba.fsync?-b.ba.fsync(b):0}catch(c){return"undefined"!==typeof U&&c instanceof L||A(c),c.ea}},
m:function(a,b,c,d){try{a:{for(var e=Y(a),f=a=0;f<c;f++){var h=Gb(e,F[b+8*f>>2],F[b+(8*f+4)>>2],void 0);if(0>h){var m=-1;break a}a+=h}m=a}F[d>>2]=m;return 0}catch(n){return"undefined"!==typeof U&&n instanceof L||A(n),n.ea}},f:function(){return la},x:function(a,b,c,d){function e(z,ka,Ka,oa,x,pa){var La=10===z?28:16;x=10===z?Wb(x):Vb(x);La=Ca(La);x=Pb(La,z,x,pa);assert(!x);x=Ca(32);F[x+4>>2]=z;F[x+8>>2]=ka;F[x+12>>2]=Ka;F[x+24>>2]=oa;F[x+20>>2]=La;F[x+16>>2]=10===z?28:16;F[x+28>>2]=0;return x}var f=
0,h=0,m=0,n=0,p=0,t=0;c&&(m=F[c>>2],n=F[c+4>>2],p=F[c+8>>2],t=F[c+12>>2]);p&&!t&&(t=2===p?17:6);!p&&t&&(p=17===t?2:1);0===t&&(t=6);0===p&&(p=1);if(!a&&!b)return-2;if(m&-1088||0!==c&&F[c>>2]&2&&!a)return-1;if(m&32)return-2;if(0!==p&&1!==p&&2!==p)return-7;if(0!==n&&2!==n&&10!==n)return-6;if(b&&(b=D(b),h=parseInt(b,10),isNaN(h)))return m&1024?-2:-8;if(!a)return 0===n&&(n=2),0===(m&1)&&(2===n?f=kc(2130706433):f=[0,0,0,1]),a=e(n,p,t,null,f,h),F[d>>2]=a,0;a=D(a);f=Mb(a);if(null!==f)if(0===n||2===n)n=2;
else if(10===n&&m&8)f=[0,0,kc(65535),f],n=10;else return-2;else if(f=Nb(a),null!==f)if(0===n||10===n)n=10;else return-2;if(null!=f)return a=e(n,p,t,a,f,h),F[d>>2]=a,0;if(m&4)return-2;a=Tb(a);f=Mb(a);0===n?n=2:10===n&&(f=[0,0,kc(65535),f]);a=e(n,p,t,null,f,h);F[d>>2]=a;return 0},k:function(a){var b=Date.now();F[a>>2]=b/1E3|0;F[a+4>>2]=b%1E3*1E3|0;return 0},i:lc,K:mc,o:function(a,b){cc();a=new Date(1E3*F[a>>2]);F[b>>2]=a.getSeconds();F[b+4>>2]=a.getMinutes();F[b+8>>2]=a.getHours();F[b+12>>2]=a.getDate();
F[b+16>>2]=a.getMonth();F[b+20>>2]=a.getFullYear()-1900;F[b+24>>2]=a.getDay();var c=new Date(a.getFullYear(),0,1);F[b+28>>2]=(a.getTime()-c.getTime())/864E5|0;F[b+36>>2]=-(60*a.getTimezoneOffset());var d=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();c=c.getTimezoneOffset();a=(d!=c&&a.getTimezoneOffset()==Math.min(c,d))|0;F[b+32>>2]=a;a=F[Z()+(a?4:0)>>2];F[b+40>>2]=a;return b},b:function(a){la=a},j:function(a){var b=Date.now()/1E3|0;a&&(F[a>>2]=b);return b}};
(function(){function a(e){g.asm=e.exports;na=g.asm.M;Ea=e=na.buffer;g.HEAP8=C=new Int8Array(e);g.HEAP16=E=new Int16Array(e);g.HEAP32=F=new Int32Array(e);g.HEAPU8=va=new Uint8Array(e);g.HEAPU16=Fa=new Uint16Array(e);g.HEAPU32=new Uint32Array(e);g.HEAPF32=new Float32Array(e);g.HEAPF64=new Float64Array(e);Ga=g.asm.P;Ia.unshift(g.asm.N);G--;g.monitorRunDependencies&&g.monitorRunDependencies(G);0==G&&(null!==Oa&&(clearInterval(Oa),Oa=null),Pa&&(e=Pa,Pa=null,e()))}function b(e){a(e.instance)}function c(e){return Ta().then(function(f){return WebAssembly.instantiate(f,
d)}).then(e,function(f){B("failed to asynchronously prepare wasm: "+f);A(f)})}var d={a:nc};G++;g.monitorRunDependencies&&g.monitorRunDependencies(G);if(g.instantiateWasm)try{return g.instantiateWasm(d,a)}catch(e){return B("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return ma||"function"!==typeof WebAssembly.instantiateStreaming||Qa()||H.startsWith("file://")||"function"!==typeof fetch?c(b):fetch(H,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,
d).then(b,function(f){B("wasm streaming compile failed: "+f);B("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();g.___wasm_call_ctors=function(){return(g.___wasm_call_ctors=g.asm.N).apply(null,arguments)};g._main=function(){return(g._main=g.asm.O).apply(null,arguments)};
var hc=g.___errno_location=function(){return(hc=g.___errno_location=g.asm.Q).apply(null,arguments)},Xb=g._ntohs=function(){return(Xb=g._ntohs=g.asm.R).apply(null,arguments)},Ca=g._malloc=function(){return(Ca=g._malloc=g.asm.S).apply(null,arguments)},Ob=g._htons=function(){return(Ob=g._htons=g.asm.T).apply(null,arguments)},kc=g._htonl=function(){return(kc=g._htonl=g.asm.U).apply(null,arguments)},Z=g.__get_tzname=function(){return(Z=g.__get_tzname=g.asm.V).apply(null,arguments)},fc=g.__get_daylight=
function(){return(fc=g.__get_daylight=g.asm.W).apply(null,arguments)},ec=g.__get_timezone=function(){return(ec=g.__get_timezone=g.asm.X).apply(null,arguments)},wa=g.stackSave=function(){return(wa=g.stackSave=g.asm.Y).apply(null,arguments)},xa=g.stackRestore=function(){return(xa=g.stackRestore=g.asm.Z).apply(null,arguments)},ta=g.stackAlloc=function(){return(ta=g.stackAlloc=g.asm._).apply(null,arguments)},ic=g._setThrew=function(){return(ic=g._setThrew=g.asm.$).apply(null,arguments)};
function lc(a,b,c){var d=wa();try{Ga.get(a)(b,c)}catch(e){xa(d);if(e!==e+0&&"longjmp"!==e)throw e;ic(1,0)}}function mc(a,b,c,d,e){var f=wa();try{Ga.get(a)(b,c,d,e)}catch(h){xa(f);if(h!==h+0&&"longjmp"!==h)throw h;ic(1,0)}}g.cwrap=function(a,b,c,d){c=c||[];var e=c.every(function(f){return"number"===f});return"string"!==b&&e&&!d?ra(a):function(){return sa(a,b,c,arguments)}};var oc;function ia(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}
Pa=function pc(){oc||qc();oc||(Pa=pc)};
function qc(a){function b(){if(!oc&&(oc=!0,g.calledRun=!0,!qa)){V.root=zb(V,null);g.noFSInit||Ib||(Ib=!0,Hb(),g.stdin=g.stdin,g.stdout=g.stdout,g.stderr=g.stderr,g.stdin?Kb("stdin",g.stdin):Cb("/dev/tty","/dev/stdin"),g.stdout?Kb("stdout",null,g.stdout):Cb("/dev/tty","/dev/stdout"),g.stderr?Kb("stderr",null,g.stderr):Cb("/dev/tty1","/dev/stderr"),Db("/dev/stdin",0),Db("/dev/stdout",1),Db("/dev/stderr",1));Ua(Ia);lb=!1;Ua(Ja);if(g.onRuntimeInitialized)g.onRuntimeInitialized();if(rc){var c=a,d=g._main;
c=c||[];var e=c.length+1,f=ta(4*(e+1));F[f>>2]=Da(aa);for(var h=1;h<e;h++)F[(f>>2)+h]=Da(c[h-1]);F[(f>>2)+e]=0;try{var m=d(e,f);jc(m,!0)}catch(n){n instanceof ia||"unwind"==n||((c=n)&&"object"===typeof n&&n.stack&&(c=[n,n.stack]),B("exception thrown: "+c),r(1,n))}finally{}}if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;)c=g.postRun.shift(),Ma.unshift(c);Ua(Ma)}}a=a||q;if(!(0<G)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Na();
Ua(Ha);0<G||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);b()},1)):b())}}g.run=qc;function jc(a,b){if(!b||!noExitRuntime||0!==a){if(!noExitRuntime){if(g.onExit)g.onExit(a);qa=!0}r(a,new ia(a))}}if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();var rc=!0;g.noInitialRun&&(rc=!1);qc();
