
var g;g||(g=typeof Module !== 'undefined' ? Module : {});var h={},l;for(l in g)g.hasOwnProperty(l)&&(h[l]=g[l]);var n=[],aa="./this.program";function r(a,b){throw b;}var ba=!1,t=!1,w=!1,ca=!1;ba="object"===typeof window;t="function"===typeof importScripts;w="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;ca=!ba&&!w&&!t;var x="",da,ea,y,fa,ha;
if(w)x=t?require("path").dirname(x)+"/":__dirname+"/",da=function(a,b){fa||(fa=require("fs"));ha||(ha=require("path"));a=ha.normalize(a);return fa.readFileSync(a,b?null:"utf8")},y=function(a){a=da(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(aa=process.argv[1].replace(/\\/g,"/")),n=process.argv.slice(2),"undefined"!==typeof module&&(module.exports=g),process.on("uncaughtException",function(a){if(!(a instanceof ia))throw a;}),process.on("unhandledRejection",
z),r=function(a){process.exit(a)},g.inspect=function(){return"[Emscripten Module object]"};else if(ca)"undefined"!=typeof read&&(da=function(a){return read(a)}),y=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?n=scriptArgs:"undefined"!=typeof arguments&&(n=arguments),"function"===typeof quit&&(r=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&
(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(ba||t)t?x=self.location.href:"undefined"!==typeof document&&document.currentScript&&(x=document.currentScript.src),x=0!==x.indexOf("blob:")?x.substr(0,x.lastIndexOf("/")+1):"",da=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},t&&(y=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),
ea=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var ka=g.print||console.log.bind(console),A=g.printErr||console.warn.bind(console);for(l in h)h.hasOwnProperty(l)&&(g[l]=h[l]);h=null;g.arguments&&(n=g.arguments);g.thisProgram&&(aa=g.thisProgram);g.quit&&(r=g.quit);var B;g.wasmBinary&&(B=g.wasmBinary);var noExitRuntime=g.noExitRuntime||!0;
"object"!==typeof WebAssembly&&z("no native wasm support detected");var la,ma=!1;function assert(a,b){a||z("Assertion failed: "+b)}function na(a){var b=g["_"+a];assert(b,"Cannot call unknown function "+a+", make sure it is exported");return b}
function oa(a,b,c,d){var e={string:function(m){var u=0;if(null!==m&&void 0!==m&&0!==m){var v=(m.length<<2)+1;u=C(v);pa(m,qa,u,v)}return u},array:function(m){var u=C(m.length);D.set(m,u);return u}},f=na(a),k=[];a=0;if(d)for(var p=0;p<d.length;p++){var q=e[c[p]];q?(0===a&&(a=ra()),k[p]=q(d[p])):k[p]=d[p]}c=f.apply(null,k);c=function(m){return"string"===b?E(m):"boolean"===b?!!m:m}(c);0!==a&&sa(a);return c}var ta="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ua(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&ta)return ta.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var k=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|k:(e&7)<<18|f<<12|k<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function E(a){return a?ua(qa,a,void 0):""}
function pa(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var k=a.charCodeAt(f);if(55296<=k&&57343>=k){var p=a.charCodeAt(++f);k=65536+((k&1023)<<10)|p&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-e}
function va(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function wa(a){var b=va(a)+1,c=xa(b);c&&pa(a,D,c,b);return c}function ya(a){var b=va(a)+1,c=C(b);pa(a,D,c,b);return c}var za,D,qa,Aa,G,Ba,Ca=[],Da=[],Ea=[],Fa=[];function Ga(){var a=g.preRun.shift();Ca.unshift(a)}var H=0,Ha=null,Ia=null;g.preloadedImages={};g.preloadedAudios={};
function z(a){if(g.onAbort)g.onAbort(a);A(a);ma=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function Ja(){return I.startsWith("data:application/octet-stream;base64,")}var I="bumblestack.wasm";if(!Ja()){var Ka=I;I=g.locateFile?g.locateFile(Ka,x):x+Ka}function La(){var a=I;try{if(a==I&&B)return new Uint8Array(B);if(y)return y(a);throw"both async and sync fetching of the wasm failed";}catch(b){z(b)}}
function Ma(){if(!B&&(ba||t)){if("function"===typeof fetch&&!I.startsWith("file://"))return fetch(I,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+I+"'";return a.arrayBuffer()}).catch(function(){return La()});if(ea)return new Promise(function(a,b){ea(I,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return La()})}var K,L;
function Na(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(g);else{var c=b.ua;"number"===typeof c?void 0===b.aa?Ba.get(c)():Ba.get(c)(b.aa):c(void 0===b.aa?null:b.aa)}}}function Oa(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}
function M(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Oa(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}function Qa(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function Ra(a){if("/"===a)return"/";a=M(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function Sa(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(w)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){z("randomDevice")}}
function Ta(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Oa(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var Ua=[];function Va(a,b){Ua[a]={input:[],output:[],X:b};Wa(a,Xa)}
var Xa={open:function(a){var b=Ua[a.node.rdev];if(!b)throw new N(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.X.flush(a.tty)},flush:function(a){a.tty.X.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.X.ia)throw new N(60);for(var e=0,f=0;f<d;f++){try{var k=a.tty.X.ia(a.tty)}catch(p){throw new N(29);}if(void 0===k&&0===e)throw new N(6);if(null===k||void 0===k)break;e++;b[c+f]=k}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.X.ba)throw new N(60);try{for(var e=
0;e<d;e++)a.tty.X.ba(a.tty,b[c+e])}catch(f){throw new N(29);}d&&(a.node.timestamp=Date.now());return e}},Ya={ia:function(a){if(!a.input.length){var b=null;if(w){var c=Buffer.ma?Buffer.ma(256):new Buffer(256),d=0;try{d=fa.readSync(process.stdin.fd,c,0,256,null)}catch(e){if(e.toString().includes("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&
(b=readline(),null!==b&&(b+="\n"));if(!b)return null;c=Array(va(b)+1);b=pa(b,c,0,c.length);c.length=b;a.input=c}return a.input.shift()},ba:function(a,b){null===b||10===b?(ka(ua(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(ka(ua(a.output,0)),a.output=[])}},Za={ba:function(a,b){null===b||10===b?(A(ua(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(A(ua(a.output,0)),a.output=[])}},O={R:null,T:function(){return O.createNode(null,
"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new N(63);O.R||(O.R={dir:{node:{P:O.K.P,S:O.K.S,lookup:O.K.lookup,$:O.K.$,rename:O.K.rename,unlink:O.K.unlink,rmdir:O.K.rmdir,readdir:O.K.readdir,symlink:O.K.symlink},stream:{V:O.M.V}},file:{node:{P:O.K.P,S:O.K.S},stream:{V:O.M.V,read:O.M.read,write:O.M.write,ea:O.M.ea,ja:O.M.ja,la:O.M.la}},link:{node:{P:O.K.P,S:O.K.S,readlink:O.K.readlink},stream:{}},fa:{node:{P:O.K.P,S:O.K.S},stream:$a}});c=ab(a,b,c,d);16384===
(c.mode&61440)?(c.K=O.R.dir.node,c.M=O.R.dir.stream,c.L={}):32768===(c.mode&61440)?(c.K=O.R.file.node,c.M=O.R.file.stream,c.N=0,c.L=null):40960===(c.mode&61440)?(c.K=O.R.link.node,c.M=O.R.link.stream):8192===(c.mode&61440)&&(c.K=O.R.fa.node,c.M=O.R.fa.stream);c.timestamp=Date.now();a&&(a.L[b]=c,a.timestamp=c.timestamp);return c},va:function(a){return a.L?a.L.subarray?a.L.subarray(0,a.N):new Uint8Array(a.L):new Uint8Array(0)},ga:function(a,b){var c=a.L?a.L.length:0;c>=b||(b=Math.max(b,c*(1048576>c?
2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.L,a.L=new Uint8Array(b),0<a.N&&a.L.set(c.subarray(0,a.N),0))},qa:function(a,b){if(a.N!=b)if(0==b)a.L=null,a.N=0;else{var c=a.L;a.L=new Uint8Array(b);c&&a.L.set(c.subarray(0,Math.min(b,a.N)));a.N=b}},K:{P:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.N:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);
b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.na=4096;b.blocks=Math.ceil(b.size/b.na);return b},S:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&O.qa(a,b.size)},lookup:function(){throw bb[44];},$:function(a,b,c,d){return O.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=P(b,c)}catch(f){}if(d)for(var e in d.L)throw new N(55);}delete a.parent.L[a.name];a.parent.timestamp=Date.now();a.name=
c;b.L[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink:function(a,b){delete a.L[b];a.timestamp=Date.now()},rmdir:function(a,b){var c=P(a,b),d;for(d in c.L)throw new N(55);delete a.L[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.L)a.L.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=O.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new N(28);return a.link}},M:{read:function(a,b,c,d,e){var f=a.node.L;
if(e>=a.node.N)return 0;a=Math.min(a.node.N-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.L||a.L.subarray)){if(f)return a.L=b.subarray(c,c+d),a.N=d;if(0===a.N&&0===e)return a.L=b.slice(c,c+d),a.N=d;if(e+d<=a.N)return a.L.set(b.subarray(c,c+d),e),d}O.ga(a,e+d);if(a.L.subarray&&b.subarray)a.L.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.L[e+f]=b[c+f];a.N=
Math.max(a.N,e+d);return d},V:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.N);if(0>b)throw new N(28);return b},ea:function(a,b,c){O.ga(a.node,b+c);a.node.N=Math.max(a.node.N,b+c)},ja:function(a,b,c,d,e,f){if(0!==b)throw new N(28);if(32768!==(a.node.mode&61440))throw new N(43);a=a.node.L;if(f&2||a.buffer!==za){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;f=65536*Math.ceil(c/65536);for(b=xa(f);c<f;)D[b+c++]=0;c=
b;if(!c)throw new N(48);D.set(a,c)}else d=!1,c=a.byteOffset;return{xa:c,ta:d}},la:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new N(43);if(e&2)return 0;O.M.write(a,b,0,d,c,!1);return 0}}},cb=null,db={},eb=[],fb=1,Q=null,gb=!0,R={},N=null,bb={};
function T(a,b){a=Ta("/",a);b=b||{};if(!a)return{path:"",node:null};var c={ha:!0,da:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.da)throw new N(32);a=Oa(a.split("/").filter(function(k){return!!k}),!1);var e=cb;c="/";for(d=0;d<a.length;d++){var f=d===a.length-1;if(f&&b.parent)break;e=P(e,a[d]);c=M(c+"/"+a[d]);e.Z&&(!f||f&&b.ha)&&(e=e.Z.root);if(!f||b.Y)for(f=0;40960===(e.mode&61440);)if(e=hb(c),c=Ta(Qa(c),e),e=T(c,{da:b.da}).node,40<f++)throw new N(32);}return{path:c,node:e}}
function ib(a){for(var b;;){if(a===a.parent)return a=a.T.ka,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function jb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Q.length}function P(a,b){var c;if(c=(c=U(a,"x"))?c:a.K.lookup?0:2)throw new N(c,a);for(c=Q[jb(a.id,b)];c;c=c.W){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.K.lookup(a,b)}function ab(a,b,c,d){a=new kb(a,b,c,d);b=jb(a.parent.id,a.name);a.W=Q[b];return Q[b]=a}
var lb={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090};function mb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function U(a,b){if(gb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function nb(a,b){try{return P(a,b),20}catch(c){}return U(a,"wx")}function ob(a){var b=4096;for(a=a||0;a<=b;a++)if(!eb[a])return a;throw new N(33);}
function pb(a,b){qb||(qb=function(){},qb.prototype={});var c=new qb,d;for(d in a)c[d]=a[d];a=c;b=ob(b);a.fd=b;return eb[b]=a}var $a={open:function(a){a.M=db[a.node.rdev].M;a.M.open&&a.M.open(a)},V:function(){throw new N(70);}};function Wa(a,b){db[a]={M:b}}
function rb(a,b){var c="/"===b,d=!b;if(c&&cb)throw new N(10);if(!c&&!d){var e=T(b,{ha:!1});b=e.path;e=e.node;if(e.Z)throw new N(10);if(16384!==(e.mode&61440))throw new N(54);}b={type:a,wa:{},ka:b,pa:[]};a=a.T(b);a.T=b;b.root=a;c?cb=a:e&&(e.Z=b,e.T&&e.T.pa.push(b))}function sb(a,b,c){var d=T(a,{parent:!0}).node;a=Ra(a);if(!a||"."===a||".."===a)throw new N(28);var e=nb(d,a);if(e)throw new N(e);if(!d.K.$)throw new N(63);return d.K.$(d,a,b,c)}
function V(a,b){return sb(a,(void 0!==b?b:511)&1023|16384,0)}function tb(a,b,c){"undefined"===typeof c&&(c=b,b=438);sb(a,b|8192,c)}function ub(a,b){if(!Ta(a))throw new N(44);var c=T(b,{parent:!0}).node;if(!c)throw new N(44);b=Ra(b);var d=nb(c,b);if(d)throw new N(d);if(!c.K.symlink)throw new N(63);c.K.symlink(c,b,a)}function hb(a){a=T(a).node;if(!a)throw new N(44);if(!a.K.readlink)throw new N(28);return Ta(ib(a.parent),a.K.readlink(a))}
function vb(a,b){a=T(a,{Y:!b}).node;if(!a)throw new N(44);if(!a.K.P)throw new N(63);return a.K.P(a)}function wb(a){return vb(a,!0)}
function xb(a,b,c,d){if(""===a)throw new N(44);if("string"===typeof b){var e=lb[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var f=a;else{a=M(a);try{f=T(a,{Y:!(b&131072)}).node}catch(k){}}e=!1;if(b&64)if(f){if(b&128)throw new N(20);}else f=sb(a,c,0),e=!0;if(!f)throw new N(44);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&16384!==(f.mode&61440))throw new N(54);if(!e&&(c=f?40960===(f.mode&61440)?32:
16384===(f.mode&61440)&&("r"!==mb(b)||b&512)?31:U(f,mb(b)):44))throw new N(c);if(b&512){c=f;c="string"===typeof c?T(c,{Y:!0}).node:c;if(!c.K.S)throw new N(63);if(16384===(c.mode&61440))throw new N(31);if(32768!==(c.mode&61440))throw new N(28);if(e=U(c,"w"))throw new N(e);c.K.S(c,{size:0,timestamp:Date.now()})}b&=-131713;d=pb({node:f,path:ib(f),flags:b,seekable:!0,position:0,M:f.M,sa:[],error:!1},d);d.M.open&&d.M.open(d);!g.logReadFiles||b&1||(yb||(yb={}),a in yb||(yb[a]=1,A("FS.trackingDelegate error on read file: "+
a)));try{R.onOpenFile&&(f=0,1!==(b&2097155)&&(f|=1),0!==(b&2097155)&&(f|=2),R.onOpenFile(a,f))}catch(k){A("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+k.message)}return d}function zb(a,b,c){if(null===a.fd)throw new N(8);if(!a.seekable||!a.M.V)throw new N(70);if(0!=c&&1!=c&&2!=c)throw new N(28);a.position=a.M.V(a,b,c);a.sa=[];return a.position}
function Ab(){N||(N=function(a,b){this.node=b;this.ra=function(c){this.O=c};this.ra(a);this.message="FS error"},N.prototype=Error(),N.prototype.constructor=N,[44].forEach(function(a){bb[a]=new N(a);bb[a].stack="<generic error, no stack>"}))}var Bb;function Cb(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function Db(a,b,c){a=M("/dev/"+a);var d=Cb(!!b,!!c);Eb||(Eb=64);var e=Eb++<<8|0;Wa(e,{open:function(f){f.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(f,k,p,q){for(var m=0,u=0;u<q;u++){try{var v=b()}catch(F){throw new N(29);}if(void 0===v&&0===m)throw new N(6);if(null===v||void 0===v)break;m++;k[p+u]=v}m&&(f.node.timestamp=Date.now());return m},write:function(f,k,p,q){for(var m=0;m<q;m++)try{c(k[p+m])}catch(u){throw new N(29);}q&&(f.node.timestamp=Date.now());return m}});
tb(a,d,e)}var Eb,W={},qb,yb,Fb=511;
function Gb(a,b,c){try{var d=a(b)}catch(e){if(e&&e.node&&M(b)!==M(ib(e.node)))return-54;throw e;}G[c>>2]=d.dev;G[c+4>>2]=0;G[c+8>>2]=d.ino;G[c+12>>2]=d.mode;G[c+16>>2]=d.nlink;G[c+20>>2]=d.uid;G[c+24>>2]=d.gid;G[c+28>>2]=d.rdev;G[c+32>>2]=0;L=[d.size>>>0,(K=d.size,1<=+Math.abs(K)?0<K?(Math.min(+Math.floor(K/4294967296),4294967295)|0)>>>0:~~+Math.ceil((K-+(~~K>>>0))/4294967296)>>>0:0)];G[c+40>>2]=L[0];G[c+44>>2]=L[1];G[c+48>>2]=4096;G[c+52>>2]=d.blocks;G[c+56>>2]=d.atime.getTime()/1E3|0;G[c+60>>2]=
0;G[c+64>>2]=d.mtime.getTime()/1E3|0;G[c+68>>2]=0;G[c+72>>2]=d.ctime.getTime()/1E3|0;G[c+76>>2]=0;L=[d.ino>>>0,(K=d.ino,1<=+Math.abs(K)?0<K?(Math.min(+Math.floor(K/4294967296),4294967295)|0)>>>0:~~+Math.ceil((K-+(~~K>>>0))/4294967296)>>>0:0)];G[c+80>>2]=L[0];G[c+84>>2]=L[1];return 0}var Hb=void 0;function X(){Hb+=4;return G[Hb-4>>2]}function Y(a){a=eb[a];if(!a)throw new N(8);return a}var Ib={};
function Jb(){if(!Kb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:aa||"./this.program"},b;for(b in Ib)a[b]=Ib[b];var c=[];for(b in a)c.push(b+"="+a[b]);Kb=c}return Kb}var Kb;
function Lb(){function a(k){return(k=k.toTimeString().match(/\(([A-Za-z ]+)\)$/))?k[1]:"GMT"}if(!Mb){Mb=!0;var b=(new Date).getFullYear(),c=new Date(b,0,1),d=new Date(b,6,1);b=c.getTimezoneOffset();var e=d.getTimezoneOffset(),f=Math.max(b,e);G[Nb()>>2]=60*f;G[Ob()>>2]=Number(b!=e);c=a(c);d=a(d);c=wa(c);d=wa(d);e<b?(G[Z()>>2]=c,G[Z()+4>>2]=d):(G[Z()>>2]=d,G[Z()+4>>2]=c)}}var Mb;
function kb(a,b,c,d){a||(a=this);this.parent=a;this.T=a.T;this.Z=null;this.id=fb++;this.name=b;this.mode=c;this.K={};this.M={};this.rdev=d}Object.defineProperties(kb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});Ab();Q=Array(4096);rb(O,"/");V("/tmp");V("/home");V("/home/web_user");
(function(){V("/dev");Wa(259,{read:function(){return 0},write:function(b,c,d,e){return e}});tb("/dev/null",259);Va(1280,Ya);Va(1536,Za);tb("/dev/tty",1280);tb("/dev/tty1",1536);var a=Sa();Db("random",a);Db("urandom",a);V("/dev/shm");V("/dev/shm/tmp")})();
(function(){V("/proc");var a=V("/proc/self");V("/proc/self/fd");rb({T:function(){var b=ab(a,"fd",16895,73);b.K={lookup:function(c,d){var e=eb[+d];if(!e)throw new N(8);c={parent:null,T:{ka:"fake"},K:{readlink:function(){return e.path}}};return c.parent=c}};return b}},"/proc/self/fd")})();
var Rb={a:function(a,b,c,d){z("Assertion failed: "+E(a)+", at: "+[b?E(b):"unknown filename",c,d?E(d):"unknown function"])},v:function(a,b){try{a=E(a);if(b&-8)var c=-28;else{var d;(d=T(a,{Y:!0}).node)?(a="",b&4&&(a+="r"),b&2&&(a+="w"),b&1&&(a+="x"),c=a&&U(d,a)?-2:0):c=-44}return c}catch(e){return"undefined"!==typeof W&&e instanceof N||z(e),-e.O}},j:function(a,b,c){Hb=c;try{var d=Y(a);switch(b){case 0:var e=X();return 0>e?-28:xb(d.path,d.flags,0,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=
X(),d.flags|=e,0;case 12:return e=X(),Aa[e+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return G[Pb()>>2]=28,-1;default:return-28}}catch(f){return"undefined"!==typeof W&&f instanceof N||z(f),-f.O}},w:function(a,b,c){try{var d=Y(a);if(!d.U){var e=T(d.path,{Y:!0}).node;if(!e.K.readdir)throw new N(54);var f=e.K.readdir(e);d.U=f}a=0;for(var k=zb(d,0,1),p=Math.floor(k/280);p<d.U.length&&a+280<=c;){var q=d.U[p];if("."===q[0]){var m=1;var u=4}else{var v=P(d.node,q);m=v.id;u=8192===
(v.mode&61440)?2:16384===(v.mode&61440)?4:40960===(v.mode&61440)?10:8}L=[m>>>0,(K=m,1<=+Math.abs(K)?0<K?(Math.min(+Math.floor(K/4294967296),4294967295)|0)>>>0:~~+Math.ceil((K-+(~~K>>>0))/4294967296)>>>0:0)];G[b+a>>2]=L[0];G[b+a+4>>2]=L[1];L=[280*(p+1)>>>0,(K=280*(p+1),1<=+Math.abs(K)?0<K?(Math.min(+Math.floor(K/4294967296),4294967295)|0)>>>0:~~+Math.ceil((K-+(~~K>>>0))/4294967296)>>>0:0)];G[b+a+8>>2]=L[0];G[b+a+12>>2]=L[1];Aa[b+a+16>>1]=280;D[b+a+18>>0]=u;pa(q,qa,b+a+19,256);a+=280;p+=1}zb(d,280*
p,0);return a}catch(F){return"undefined"!==typeof W&&F instanceof N||z(F),-F.O}},x:function(a,b,c){Hb=c;try{var d=Y(a);switch(b){case 21509:case 21505:return d.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.tty?0:-59;case 21519:if(!d.tty)return-59;var e=X();return G[e>>2]=0;case 21520:return d.tty?-28:-59;case 21531:a=e=X();if(!d.M.oa)throw new N(59);return d.M.oa(d,b,a);case 21523:return d.tty?0:-59;case 21524:return d.tty?0:-59;default:z("bad ioctl syscall "+
b)}}catch(f){return"undefined"!==typeof W&&f instanceof N||z(f),-f.O}},r:function(a,b){try{return a=E(a),Gb(wb,a,b)}catch(c){return"undefined"!==typeof W&&c instanceof N||z(c),-c.O}},s:function(a,b){try{return a=E(a),a=M(a),"/"===a[a.length-1]&&(a=a.substr(0,a.length-1)),V(a,b),0}catch(c){return"undefined"!==typeof W&&c instanceof N||z(c),-c.O}},g:function(a,b,c){Hb=c;try{var d=E(a),e=c?X():0;return xb(d,b,e).fd}catch(f){return"undefined"!==typeof W&&f instanceof N||z(f),-f.O}},t:function(a,b){try{return a=
E(a),Gb(vb,a,b)}catch(c){return"undefined"!==typeof W&&c instanceof N||z(c),-c.O}},q:function(a){try{var b=Fb;Fb=a;return b}catch(c){return"undefined"!==typeof W&&c instanceof N||z(c),-c.O}},u:function(a){try{a=E(a);var b=T(a,{parent:!0}).node,c=Ra(a),d=P(b,c);a:{try{var e=P(b,c)}catch(m){var f=m.O;break a}var k=U(b,"wx");f=k?k:16384===(e.mode&61440)?31:0}if(f)throw new N(f);if(!b.K.unlink)throw new N(63);if(d.Z)throw new N(10);try{R.willDeletePath&&R.willDeletePath(a)}catch(m){A("FS.trackingDelegate['willDeletePath']('"+
a+"') threw an exception: "+m.message)}b.K.unlink(b,c);var p=jb(d.parent.id,d.name);if(Q[p]===d)Q[p]=d.W;else for(var q=Q[p];q;){if(q.W===d){q.W=d.W;break}q=q.W}try{if(R.onDeletePath)R.onDeletePath(a)}catch(m){A("FS.trackingDelegate['onDeletePath']('"+a+"') threw an exception: "+m.message)}return 0}catch(m){return"undefined"!==typeof W&&m instanceof N||z(m),-m.O}},b:function(){z()},m:function(a,b,c){qa.copyWithin(a,b,b+c)},n:function(){z("OOM")},o:function(a,b){try{var c=0;Jb().forEach(function(d,
e){var f=b+c;e=G[a+4*e>>2]=f;for(f=0;f<d.length;++f)D[e++>>0]=d.charCodeAt(f);D[e>>0]=0;c+=d.length+1});return 0}catch(d){return"undefined"!==typeof W&&d instanceof N||z(d),d.O}},p:function(a,b){try{var c=Jb();G[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});G[b>>2]=d;return 0}catch(e){return"undefined"!==typeof W&&e instanceof N||z(e),e.O}},c:function(a){Qb(a)},d:function(a){try{var b=Y(a);if(null===b.fd)throw new N(8);b.U&&(b.U=null);try{b.M.close&&b.M.close(b)}catch(c){throw c;}finally{eb[b.fd]=
null}b.fd=null;return 0}catch(c){return"undefined"!==typeof W&&c instanceof N||z(c),c.O}},f:function(a,b,c,d){try{a:{for(var e=Y(a),f=a=0;f<c;f++){var k=G[b+(8*f+4)>>2],p=e,q=G[b+8*f>>2],m=k,u=void 0,v=D;if(0>m||0>u)throw new N(28);if(null===p.fd)throw new N(8);if(1===(p.flags&2097155))throw new N(8);if(16384===(p.node.mode&61440))throw new N(31);if(!p.M.read)throw new N(28);var F="undefined"!==typeof u;if(!F)u=p.position;else if(!p.seekable)throw new N(70);var ja=p.M.read(p,v,q,m,u);F||(p.position+=
ja);var S=ja;if(0>S){var J=-1;break a}a+=S;if(S<k)break}J=a}G[d>>2]=J;return 0}catch(Pa){return"undefined"!==typeof W&&Pa instanceof N||z(Pa),Pa.O}},l:function(a,b,c,d,e){try{var f=Y(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;zb(f,a,d);L=[f.position>>>0,(K=f.position,1<=+Math.abs(K)?0<K?(Math.min(+Math.floor(K/4294967296),4294967295)|0)>>>0:~~+Math.ceil((K-+(~~K>>>0))/4294967296)>>>0:0)];G[e>>2]=L[0];G[e+4>>2]=L[1];f.U&&0===a&&0===d&&(f.U=null);return 0}catch(k){return"undefined"!==
typeof W&&k instanceof N||z(k),k.O}},e:function(a,b,c,d){try{a:{for(var e=Y(a),f=a=0;f<c;f++){var k=e,p=G[b+8*f>>2],q=G[b+(8*f+4)>>2],m=void 0,u=D;if(0>q||0>m)throw new N(28);if(null===k.fd)throw new N(8);if(0===(k.flags&2097155))throw new N(8);if(16384===(k.node.mode&61440))throw new N(31);if(!k.M.write)throw new N(28);k.seekable&&k.flags&1024&&zb(k,0,2);var v="undefined"!==typeof m;if(!v)m=k.position;else if(!k.seekable)throw new N(70);var F=k.M.write(k,u,p,q,m,void 0);v||(k.position+=F);try{if(k.path&&
R.onWriteToFile)R.onWriteToFile(k.path)}catch(J){A("FS.trackingDelegate['onWriteToFile']('"+k.path+"') threw an exception: "+J.message)}var ja=F;if(0>ja){var S=-1;break a}a+=ja}S=a}G[d>>2]=S;return 0}catch(J){return"undefined"!==typeof W&&J instanceof N||z(J),J.O}},h:function(a){var b=Date.now();G[a>>2]=b/1E3|0;G[a+4>>2]=b%1E3*1E3|0;return 0},k:function(a,b){Lb();a=new Date(1E3*G[a>>2]);G[b>>2]=a.getSeconds();G[b+4>>2]=a.getMinutes();G[b+8>>2]=a.getHours();G[b+12>>2]=a.getDate();G[b+16>>2]=a.getMonth();
G[b+20>>2]=a.getFullYear()-1900;G[b+24>>2]=a.getDay();var c=new Date(a.getFullYear(),0,1);G[b+28>>2]=(a.getTime()-c.getTime())/864E5|0;G[b+36>>2]=-(60*a.getTimezoneOffset());var d=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();c=c.getTimezoneOffset();a=(d!=c&&a.getTimezoneOffset()==Math.min(c,d))|0;G[b+32>>2]=a;a=G[Z()+(a?4:0)>>2];G[b+40>>2]=a;return b},i:function(a){var b=Date.now()/1E3|0;a&&(G[a>>2]=b);return b}};
(function(){function a(e){g.asm=e.exports;la=g.asm.y;za=e=la.buffer;g.HEAP8=D=new Int8Array(e);g.HEAP16=Aa=new Int16Array(e);g.HEAP32=G=new Int32Array(e);g.HEAPU8=qa=new Uint8Array(e);g.HEAPU16=new Uint16Array(e);g.HEAPU32=new Uint32Array(e);g.HEAPF32=new Float32Array(e);g.HEAPF64=new Float64Array(e);Ba=g.asm.B;Da.unshift(g.asm.z);H--;g.monitorRunDependencies&&g.monitorRunDependencies(H);0==H&&(null!==Ha&&(clearInterval(Ha),Ha=null),Ia&&(e=Ia,Ia=null,e()))}function b(e){a(e.instance)}function c(e){return Ma().then(function(f){return WebAssembly.instantiate(f,
d)}).then(e,function(f){A("failed to asynchronously prepare wasm: "+f);z(f)})}var d={a:Rb};H++;g.monitorRunDependencies&&g.monitorRunDependencies(H);if(g.instantiateWasm)try{return g.instantiateWasm(d,a)}catch(e){return A("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return B||"function"!==typeof WebAssembly.instantiateStreaming||Ja()||I.startsWith("file://")||"function"!==typeof fetch?c(b):fetch(I,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,
d).then(b,function(f){A("wasm streaming compile failed: "+f);A("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();g.___wasm_call_ctors=function(){return(g.___wasm_call_ctors=g.asm.z).apply(null,arguments)};g._main=function(){return(g._main=g.asm.A).apply(null,arguments)};
var xa=g._malloc=function(){return(xa=g._malloc=g.asm.C).apply(null,arguments)},Pb=g.___errno_location=function(){return(Pb=g.___errno_location=g.asm.D).apply(null,arguments)},Z=g.__get_tzname=function(){return(Z=g.__get_tzname=g.asm.E).apply(null,arguments)},Ob=g.__get_daylight=function(){return(Ob=g.__get_daylight=g.asm.F).apply(null,arguments)},Nb=g.__get_timezone=function(){return(Nb=g.__get_timezone=g.asm.G).apply(null,arguments)},ra=g.stackSave=function(){return(ra=g.stackSave=g.asm.H).apply(null,
arguments)},sa=g.stackRestore=function(){return(sa=g.stackRestore=g.asm.I).apply(null,arguments)},C=g.stackAlloc=function(){return(C=g.stackAlloc=g.asm.J).apply(null,arguments)};g.cwrap=function(a,b,c,d){c=c||[];var e=c.every(function(f){return"number"===f});return"string"!==b&&e&&!d?na(a):function(){return oa(a,b,c,arguments)}};var Sb;function ia(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Ia=function Tb(){Sb||Ub();Sb||(Ia=Tb)};
function Ub(a){function b(){if(!Sb&&(Sb=!0,g.calledRun=!0,!ma)){g.noFSInit||Bb||(Bb=!0,Ab(),g.stdin=g.stdin,g.stdout=g.stdout,g.stderr=g.stderr,g.stdin?Db("stdin",g.stdin):ub("/dev/tty","/dev/stdin"),g.stdout?Db("stdout",null,g.stdout):ub("/dev/tty","/dev/stdout"),g.stderr?Db("stderr",null,g.stderr):ub("/dev/tty1","/dev/stderr"),xb("/dev/stdin",0),xb("/dev/stdout",1),xb("/dev/stderr",1));Na(Da);gb=!1;Na(Ea);if(g.onRuntimeInitialized)g.onRuntimeInitialized();if(Vb){var c=a,d=g._main;c=c||[];var e=
c.length+1,f=C(4*(e+1));G[f>>2]=ya(aa);for(var k=1;k<e;k++)G[(f>>2)+k]=ya(c[k-1]);G[(f>>2)+e]=0;try{var p=d(e,f);Qb(p,!0)}catch(q){q instanceof ia||"unwind"==q||((c=q)&&"object"===typeof q&&q.stack&&(c=[q,q.stack]),A("exception thrown: "+c),r(1,q))}finally{}}if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;)c=g.postRun.shift(),Fa.unshift(c);Na(Fa)}}a=a||n;if(!(0<H)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Ga();Na(Ca);
0<H||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);b()},1)):b())}}g.run=Ub;function Qb(a,b){if(!b||!noExitRuntime||0!==a){if(!noExitRuntime){if(g.onExit)g.onExit(a);ma=!0}r(a,new ia(a))}}if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();var Vb=!0;g.noInitialRun&&(Vb=!1);Ub();
